<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rg.proto

namespace GPBMetadata;

class Rg
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x80\x05\x0A\x08rg.proto\x12\x0Fmilvus.proto.rg\"&\x0A\x12ResourceGroupLimit\x12\x10\x0A\x08node_num\x18\x01 \x01(\x05\"/\x0A\x15ResourceGroupTransfer\x12\x16\x0A\x0Eresource_group\x18\x01 \x01(\x09\"Q\x0A\x17ResourceGroupNodeFilter\x126\x0A\x0Bnode_labels\x18\x01 \x03(\x0B2!.milvus.proto.common.KeyValuePair\"\xBC\x02\x0A\x13ResourceGroupConfig\x125\x0A\x08requests\x18\x01 \x01(\x0B2#.milvus.proto.rg.ResourceGroupLimit\x123\x0A\x06limits\x18\x02 \x01(\x0B2#.milvus.proto.rg.ResourceGroupLimit\x12=\x0A\x0Dtransfer_from\x18\x03 \x03(\x0B2&.milvus.proto.rg.ResourceGroupTransfer\x12;\x0A\x0Btransfer_to\x18\x04 \x03(\x0B2&.milvus.proto.rg.ResourceGroupTransfer\x12=\x0A\x0Bnode_filter\x18\x05 \x01(\x0B2(.milvus.proto.rg.ResourceGroupNodeFilterBp\x0A\x0Eio.milvus.grpcB\x12ResourceGroupProtoP\x01Z0github.com/milvus-io/milvus-proto/go-api/v2/rgpb\xA0\x01\x01\xAA\x02\x12Milvus.Client.Grpcb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

