<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tokenizer.proto

namespace GPBMetadata;

class Tokenizer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xAB\x04\x0A\x0Ftokenizer.proto\x12\x16milvus.proto.tokenizer\"\x98\x01\x0A\x13TokenizationRequest\x12\x0C\x0A\x04text\x18\x01 \x01(\x09\x12I\x0A\x0Aparameters\x18\x02 \x03(\x0B25.milvus.proto.tokenizer.TokenizationRequest.Parameter\x1A(\x0A\x09Parameter\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0E\x0A\x06values\x18\x02 \x03(\x09\"E\x0A\x14TokenizationResponse\x12-\x0A\x06tokens\x18\x01 \x03(\x0B2\x1D.milvus.proto.tokenizer.Token\"h\x0A\x05Token\x12\x0C\x0A\x04text\x18\x01 \x01(\x09\x12\x13\x0A\x0Boffset_from\x18\x02 \x01(\x05\x12\x11\x0A\x09offset_to\x18\x03 \x01(\x05\x12\x10\x0A\x08position\x18\x04 \x01(\x05\x12\x17\x0A\x0Fposition_length\x18\x05 \x01(\x052t\x0A\x09Tokenizer\x12g\x0A\x08Tokenize\x12+.milvus.proto.tokenizer.TokenizationRequest\x1A,.milvus.proto.tokenizer.TokenizationResponse\"\x00B6Z4github.com/milvus-io/milvus-proto/go-api/v3/schemapbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

