<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus\AlterCollectionSchemaRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Action to perform on the collection schema
 *
 * Generated from protobuf message <code>milvus.proto.milvus.AlterCollectionSchemaRequest.Action</code>
 */
class Action extends \Google\Protobuf\Internal\Message
{
    protected $op;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Milvus\AlterCollectionSchemaRequest\AddRequest $add_request
     *     @type \Milvus\Proto\Milvus\AlterCollectionSchemaRequest\DropRequest $drop_request
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.AlterCollectionSchemaRequest.AddRequest add_request = 1;</code>
     * @return \Milvus\Proto\Milvus\AlterCollectionSchemaRequest\AddRequest|null
     */
    public function getAddRequest()
    {
        return $this->readOneof(1);
    }

    public function hasAddRequest()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.AlterCollectionSchemaRequest.AddRequest add_request = 1;</code>
     * @param \Milvus\Proto\Milvus\AlterCollectionSchemaRequest\AddRequest $var
     * @return $this
     */
    public function setAddRequest(\Milvus\Proto\Milvus\AlterCollectionSchemaRequest\AddRequest|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.AlterCollectionSchemaRequest.DropRequest drop_request = 2;</code>
     * @return \Milvus\Proto\Milvus\AlterCollectionSchemaRequest\DropRequest|null
     */
    public function getDropRequest()
    {
        return $this->readOneof(2);
    }

    public function hasDropRequest()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.AlterCollectionSchemaRequest.DropRequest drop_request = 2;</code>
     * @param \Milvus\Proto\Milvus\AlterCollectionSchemaRequest\DropRequest $var
     * @return $this
     */
    public function setDropRequest(\Milvus\Proto\Milvus\AlterCollectionSchemaRequest\DropRequest|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOp()
    {
        return $this->whichOneof("op");
    }

}

