<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tokenizer.proto

namespace Milvus\Proto\Tokenizer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.tokenizer.TokenizationResponse</code>
 */
class TokenizationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.tokenizer.Token tokens = 1;</code>
     */
    private $tokens;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Tokenizer\Token[] $tokens
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tokenizer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.tokenizer.Token tokens = 1;</code>
     * @return RepeatedField<\Milvus\Proto\Tokenizer\Token>
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.tokenizer.Token tokens = 1;</code>
     * @param \Milvus\Proto\Tokenizer\Token[] $var
     * @return $this
     */
    public function setTokens(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Tokenizer\Token::class);
        $this->tokens = $arr;

        return $this;
    }

}

