<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tokenizer.proto

namespace Milvus\Proto\Tokenizer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.tokenizer.Token</code>
 */
class Token extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string text = 1;</code>
     */
    protected $text = '';
    /**
     * Generated from protobuf field <code>int32 offset_from = 2;</code>
     */
    protected $offset_from = 0;
    /**
     * Generated from protobuf field <code>int32 offset_to = 3;</code>
     */
    protected $offset_to = 0;
    /**
     * Generated from protobuf field <code>int32 position = 4;</code>
     */
    protected $position = 0;
    /**
     * Generated from protobuf field <code>int32 position_length = 5;</code>
     */
    protected $position_length = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $text
     *     @type int $offset_from
     *     @type int $offset_to
     *     @type int $position
     *     @type int $position_length
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tokenizer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string text = 1;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setText(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 offset_from = 2;</code>
     * @return int
     */
    public function getOffsetFrom()
    {
        return $this->offset_from;
    }

    /**
     * Generated from protobuf field <code>int32 offset_from = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOffsetFrom(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->offset_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 offset_to = 3;</code>
     * @return int
     */
    public function getOffsetTo()
    {
        return $this->offset_to;
    }

    /**
     * Generated from protobuf field <code>int32 offset_to = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOffsetTo(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->offset_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 position = 4;</code>
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Generated from protobuf field <code>int32 position = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPosition(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 position_length = 5;</code>
     * @return int
     */
    public function getPositionLength()
    {
        return $this->position_length;
    }

    /**
     * Generated from protobuf field <code>int32 position_length = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPositionLength(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->position_length = $var;

        return $this;
    }

}

