<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg.proto

namespace Milvus\Proto\Msg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.msg.ImportMsg</code>
 */
class ImportMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     */
    protected $collection_name = '';
    /**
     * Generated from protobuf field <code>int64 collectionID = 4;</code>
     */
    protected $collectionID = 0;
    /**
     * Generated from protobuf field <code>repeated int64 partitionIDs = 5;</code>
     */
    private $partitionIDs;
    /**
     * Generated from protobuf field <code>map<string, string> options = 6;</code>
     */
    private $options;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.ImportFile files = 7;</code>
     */
    private $files;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 8;</code>
     */
    protected $schema = null;
    /**
     * Generated from protobuf field <code>int64 jobID = 9;</code>
     */
    protected $jobID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $db_name
     *     @type string $collection_name
     *     @type int|string $collectionID
     *     @type int[]|string[] $partitionIDs
     *     @type array|\Google\Protobuf\Internal\MapField $options
     *     @type \Milvus\Proto\Msg\ImportFile[] $files
     *     @type \Milvus\Proto\Schema\CollectionSchema $schema
     *     @type int|string $jobID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Msg::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 4;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 partitionIDs = 5;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getPartitionIDs()
    {
        return $this->partitionIDs;
    }

    /**
     * Generated from protobuf field <code>repeated int64 partitionIDs = 5;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setPartitionIDs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->partitionIDs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> options = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>map<string, string> options = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOptions(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->options = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.ImportFile files = 7;</code>
     * @return RepeatedField<\Milvus\Proto\Msg\ImportFile>
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.ImportFile files = 7;</code>
     * @param \Milvus\Proto\Msg\ImportFile[] $var
     * @return $this
     */
    public function setFiles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Msg\ImportFile::class);
        $this->files = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 8;</code>
     * @return \Milvus\Proto\Schema\CollectionSchema|null
     */
    public function getSchema()
    {
        return $this->schema;
    }

    public function hasSchema()
    {
        return isset($this->schema);
    }

    public function clearSchema()
    {
        unset($this->schema);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 8;</code>
     * @param \Milvus\Proto\Schema\CollectionSchema $var
     * @return $this
     */
    public function setSchema(\Milvus\Proto\Schema\CollectionSchema|null $var)
    {
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 jobID = 9;</code>
     * @return int|string
     */
    public function getJobID()
    {
        return $this->jobID;
    }

    /**
     * Generated from protobuf field <code>int64 jobID = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJobID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->jobID = $var;

        return $this;
    }

}

