<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg.proto

namespace Milvus\Proto\Msg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.msg.InsertRequest</code>
 */
class InsertRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string shardName = 2;</code>
     */
    protected $shardName = '';
    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>string collection_name = 4;</code>
     */
    protected $collection_name = '';
    /**
     * Generated from protobuf field <code>string partition_name = 5;</code>
     */
    protected $partition_name = '';
    /**
     * Generated from protobuf field <code>int64 dbID = 6;</code>
     */
    protected $dbID = 0;
    /**
     * Generated from protobuf field <code>int64 collectionID = 7;</code>
     */
    protected $collectionID = 0;
    /**
     * Generated from protobuf field <code>int64 partitionID = 8;</code>
     */
    protected $partitionID = 0;
    /**
     * Generated from protobuf field <code>int64 segmentID = 9;</code>
     */
    protected $segmentID = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 timestamps = 10;</code>
     */
    private $timestamps;
    /**
     * Generated from protobuf field <code>repeated int64 rowIDs = 11;</code>
     */
    private $rowIDs;
    /**
     * row_data was reserved for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.Blob row_data = 12;</code>
     */
    private $row_data;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 13;</code>
     */
    private $fields_data;
    /**
     * Generated from protobuf field <code>uint64 num_rows = 14;</code>
     */
    protected $num_rows = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.msg.InsertDataVersion version = 15;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>optional string namespace = 16;</code>
     */
    protected $namespace = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $shardName
     *     @type string $db_name
     *     @type string $collection_name
     *     @type string $partition_name
     *     @type int|string $dbID
     *     @type int|string $collectionID
     *     @type int|string $partitionID
     *     @type int|string $segmentID
     *     @type int[]|string[] $timestamps
     *     @type int[]|string[] $rowIDs
     *     @type \Milvus\Proto\Common\Blob[] $row_data
     *           row_data was reserved for compatibility
     *     @type \Milvus\Proto\Schema\FieldData[] $fields_data
     *     @type int|string $num_rows
     *     @type int $version
     *     @type string $namespace
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Msg::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shardName = 2;</code>
     * @return string
     */
    public function getShardName()
    {
        return $this->shardName;
    }

    /**
     * Generated from protobuf field <code>string shardName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShardName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shardName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 4;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string partition_name = 5;</code>
     * @return string
     */
    public function getPartitionName()
    {
        return $this->partition_name;
    }

    /**
     * Generated from protobuf field <code>string partition_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPartitionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->partition_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 dbID = 6;</code>
     * @return int|string
     */
    public function getDbID()
    {
        return $this->dbID;
    }

    /**
     * Generated from protobuf field <code>int64 dbID = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDbID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->dbID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 7;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 partitionID = 8;</code>
     * @return int|string
     */
    public function getPartitionID()
    {
        return $this->partitionID;
    }

    /**
     * Generated from protobuf field <code>int64 partitionID = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartitionID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->partitionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 9;</code>
     * @return int|string
     */
    public function getSegmentID()
    {
        return $this->segmentID;
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSegmentID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->segmentID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 timestamps = 10;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getTimestamps()
    {
        return $this->timestamps;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 timestamps = 10;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setTimestamps(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->timestamps = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 rowIDs = 11;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getRowIDs()
    {
        return $this->rowIDs;
    }

    /**
     * Generated from protobuf field <code>repeated int64 rowIDs = 11;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setRowIDs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->rowIDs = $arr;

        return $this;
    }

    /**
     * row_data was reserved for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.Blob row_data = 12;</code>
     * @return RepeatedField<\Milvus\Proto\Common\Blob>
     */
    public function getRowData()
    {
        return $this->row_data;
    }

    /**
     * row_data was reserved for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.Blob row_data = 12;</code>
     * @param \Milvus\Proto\Common\Blob[] $var
     * @return $this
     */
    public function setRowData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\Blob::class);
        $this->row_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 13;</code>
     * @return RepeatedField<\Milvus\Proto\Schema\FieldData>
     */
    public function getFieldsData()
    {
        return $this->fields_data;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 13;</code>
     * @param \Milvus\Proto\Schema\FieldData[] $var
     * @return $this
     */
    public function setFieldsData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldData::class);
        $this->fields_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 num_rows = 14;</code>
     * @return int|string
     */
    public function getNumRows()
    {
        return $this->num_rows;
    }

    /**
     * Generated from protobuf field <code>uint64 num_rows = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumRows(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->num_rows = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.InsertDataVersion version = 15;</code>
     * @return int one of the values in {@see \Milvus\Proto\Msg\InsertDataVersion}
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.InsertDataVersion version = 15;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Msg\InsertDataVersion}
     * @return $this
     */
    public function setVersion(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Msg\InsertDataVersion::class);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string namespace = 16;</code>
     * @return string
     */
    public function getNamespace()
    {
        return isset($this->namespace) ? $this->namespace : '';
    }

    public function hasNamespace()
    {
        return isset($this->namespace);
    }

    public function clearNamespace()
    {
        unset($this->namespace);
    }

    /**
     * Generated from protobuf field <code>optional string namespace = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

}

