<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg.proto

namespace Milvus\Proto\Msg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.msg.ReplicateMsg</code>
 */
class ReplicateMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>bool is_end = 2;</code>
     */
    protected $is_end = false;
    /**
     * Generated from protobuf field <code>bool is_cluster = 3;</code>
     */
    protected $is_cluster = false;
    /**
     * Generated from protobuf field <code>string database = 4;</code>
     */
    protected $database = '';
    /**
     * Generated from protobuf field <code>string collection = 5;</code>
     */
    protected $collection = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type bool $is_end
     *     @type bool $is_cluster
     *     @type string $database
     *     @type string $collection
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Msg::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_end = 2;</code>
     * @return bool
     */
    public function getIsEnd()
    {
        return $this->is_end;
    }

    /**
     * Generated from protobuf field <code>bool is_end = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEnd(bool $var)
    {
        $this->is_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_cluster = 3;</code>
     * @return bool
     */
    public function getIsCluster()
    {
        return $this->is_cluster;
    }

    /**
     * Generated from protobuf field <code>bool is_cluster = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCluster(bool $var)
    {
        $this->is_cluster = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string database = 4;</code>
     * @return string
     */
    public function getDatabase()
    {
        return $this->database;
    }

    /**
     * Generated from protobuf field <code>string database = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDatabase(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->database = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection = 5;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection = $var;

        return $this;
    }

}

