<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rg.proto

namespace Milvus\Proto\Rg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.rg.ResourceGroupNodeFilter</code>
 */
class ResourceGroupNodeFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * node in resource group must match node labels requirements
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair node_labels = 1;</code>
     */
    private $node_labels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\KeyValuePair[] $node_labels
     *           node in resource group must match node labels requirements
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rg::initOnce();
        parent::__construct($data);
    }

    /**
     * node in resource group must match node labels requirements
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair node_labels = 1;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getNodeLabels()
    {
        return $this->node_labels;
    }

    /**
     * node in resource group must match node labels requirements
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair node_labels = 1;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setNodeLabels(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->node_labels = $arr;

        return $this;
    }

}

