<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rg.proto

namespace Milvus\Proto\Rg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.rg.ResourceGroupTransfer</code>
 */
class ResourceGroupTransfer extends \Google\Protobuf\Internal\Message
{
    /**
     * resource groups can be transfered with current resource group.
     *
     * Generated from protobuf field <code>string resource_group = 1;</code>
     */
    protected $resource_group = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $resource_group
     *           resource groups can be transfered with current resource group.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rg::initOnce();
        parent::__construct($data);
    }

    /**
     * resource groups can be transfered with current resource group.
     *
     * Generated from protobuf field <code>string resource_group = 1;</code>
     * @return string
     */
    public function getResourceGroup()
    {
        return $this->resource_group;
    }

    /**
     * resource groups can be transfered with current resource group.
     *
     * Generated from protobuf field <code>string resource_group = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceGroup(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->resource_group = $var;

        return $this;
    }

}

