<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema\FieldPartialUpdateOp;

use UnexpectedValueException;

/**
 * Protobuf type <code>milvus.proto.schema.FieldPartialUpdateOp.OpType</code>
 */
class OpType
{
    /**
     * REPLACE overwrites the field with the new values. Default behavior
     * when no op targets a field. Applicable to all field types.
     *
     * Generated from protobuf enum <code>REPLACE = 0;</code>
     */
    const REPLACE = 0;
    /**
     * ARRAY_APPEND appends the new values to the tail of the existing
     * array. Requires DataType_Array. The resulting length must not
     * exceed the field's max_capacity.
     *
     * Generated from protobuf enum <code>ARRAY_APPEND = 1;</code>
     */
    const ARRAY_APPEND = 1;
    /**
     * ARRAY_REMOVE removes every occurrence of each provided value from
     * the existing array. Requires DataType_Array. No-op when the base
     * array is empty or no element matches.
     *
     * Generated from protobuf enum <code>ARRAY_REMOVE = 2;</code>
     */
    const ARRAY_REMOVE = 2;

    private static $valueToName = [
        self::REPLACE => 'REPLACE',
        self::ARRAY_APPEND => 'ARRAY_APPEND',
        self::ARRAY_REMOVE => 'ARRAY_REMOVE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

