<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.schema.BucketKeyEntry</code>
 */
class BucketKeyEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 field_id = 1;</code>
     */
    protected $field_id = 0;
    /**
     * Generated from protobuf field <code>string field_name = 2;</code>
     */
    protected $field_name = '';
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $field_id
     *     @type string $field_name
     *     @type int|string $int_val
     *     @type string $string_val
     *     @type bool $bool_val
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 field_id = 1;</code>
     * @return int|string
     */
    public function getFieldId()
    {
        return $this->field_id;
    }

    /**
     * Generated from protobuf field <code>int64 field_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFieldId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->field_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string field_name = 2;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>string field_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->field_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 int_val = 3;</code>
     * @return int|string
     */
    public function getIntVal()
    {
        return $this->readOneof(3);
    }

    public function hasIntVal()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>int64 int_val = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntVal(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_val = 4;</code>
     * @return string
     */
    public function getStringVal()
    {
        return $this->readOneof(4);
    }

    public function hasStringVal()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>string string_val = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStringVal(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool_val = 5;</code>
     * @return bool
     */
    public function getBoolVal()
    {
        return $this->readOneof(5);
    }

    public function hasBoolVal()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>bool bool_val = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolVal(bool $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

