<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * \@brief Collection schema
 *
 * Generated from protobuf message <code>milvus.proto.schema.CollectionSchema</code>
 */
class CollectionSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * deprecated later, keep compatible with c++ part now
     *
     * Generated from protobuf field <code>bool autoID = 3 [deprecated = true];</code>
     * @deprecated
     */
    protected $autoID = false;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldSchema fields = 4;</code>
     */
    private $fields;
    /**
     * mark whether this table has the dynamic field function enabled.
     *
     * Generated from protobuf field <code>bool enable_dynamic_field = 5;</code>
     */
    protected $enable_dynamic_field = false;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair properties = 6;</code>
     */
    private $properties;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FunctionSchema functions = 7;</code>
     */
    private $functions;
    /**
     * Generated from protobuf field <code>string dbName = 8;</code>
     */
    protected $dbName = '';
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.StructArrayFieldSchema struct_array_fields = 9;</code>
     */
    private $struct_array_fields;
    /**
     * The version of current collection schema updates, increment every time the schema content is updating, 
     *
     * Generated from protobuf field <code>int32 version = 10;</code>
     */
    protected $version = 0;
    /**
     * 0 when the collection is created or the collection schema is updated before 2.6.5.
     * the name dbName and description take no effect to it.
     *
     * Generated from protobuf field <code>bool enable_namespace = 15;</code>
     */
    protected $enable_namespace = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $description
     *     @type bool $autoID
     *           deprecated later, keep compatible with c++ part now
     *     @type \Milvus\Proto\Schema\FieldSchema[] $fields
     *     @type bool $enable_dynamic_field
     *           mark whether this table has the dynamic field function enabled.
     *     @type \Milvus\Proto\Common\KeyValuePair[] $properties
     *     @type \Milvus\Proto\Schema\FunctionSchema[] $functions
     *     @type string $dbName
     *     @type \Milvus\Proto\Schema\StructArrayFieldSchema[] $struct_array_fields
     *     @type int $version
     *           The version of current collection schema updates, increment every time the schema content is updating, 
     *     @type bool $enable_namespace
     *           0 when the collection is created or the collection schema is updated before 2.6.5.
     *           the name dbName and description take no effect to it.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

    /**
     * deprecated later, keep compatible with c++ part now
     *
     * Generated from protobuf field <code>bool autoID = 3 [deprecated = true];</code>
     * @return bool
     * @deprecated
     */
    public function getAutoID()
    {
        if ($this->autoID !== false) {
            @trigger_error('autoID is deprecated.', E_USER_DEPRECATED);
        }
        return $this->autoID;
    }

    /**
     * deprecated later, keep compatible with c++ part now
     *
     * Generated from protobuf field <code>bool autoID = 3 [deprecated = true];</code>
     * @param bool $var
     * @return $this
     * @deprecated
     */
    public function setAutoID(bool $var)
    {
        @trigger_error('autoID is deprecated.', E_USER_DEPRECATED);
        $this->autoID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldSchema fields = 4;</code>
     * @return RepeatedField<\Milvus\Proto\Schema\FieldSchema>
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldSchema fields = 4;</code>
     * @param \Milvus\Proto\Schema\FieldSchema[] $var
     * @return $this
     */
    public function setFields(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldSchema::class);
        $this->fields = $arr;

        return $this;
    }

    /**
     * mark whether this table has the dynamic field function enabled.
     *
     * Generated from protobuf field <code>bool enable_dynamic_field = 5;</code>
     * @return bool
     */
    public function getEnableDynamicField()
    {
        return $this->enable_dynamic_field;
    }

    /**
     * mark whether this table has the dynamic field function enabled.
     *
     * Generated from protobuf field <code>bool enable_dynamic_field = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableDynamicField(bool $var)
    {
        $this->enable_dynamic_field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair properties = 6;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair properties = 6;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FunctionSchema functions = 7;</code>
     * @return RepeatedField<\Milvus\Proto\Schema\FunctionSchema>
     */
    public function getFunctions()
    {
        return $this->functions;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FunctionSchema functions = 7;</code>
     * @param \Milvus\Proto\Schema\FunctionSchema[] $var
     * @return $this
     */
    public function setFunctions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FunctionSchema::class);
        $this->functions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dbName = 8;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->dbName;
    }

    /**
     * Generated from protobuf field <code>string dbName = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->dbName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.StructArrayFieldSchema struct_array_fields = 9;</code>
     * @return RepeatedField<\Milvus\Proto\Schema\StructArrayFieldSchema>
     */
    public function getStructArrayFields()
    {
        return $this->struct_array_fields;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.StructArrayFieldSchema struct_array_fields = 9;</code>
     * @param \Milvus\Proto\Schema\StructArrayFieldSchema[] $var
     * @return $this
     */
    public function setStructArrayFields(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\StructArrayFieldSchema::class);
        $this->struct_array_fields = $arr;

        return $this;
    }

    /**
     * The version of current collection schema updates, increment every time the schema content is updating, 
     *
     * Generated from protobuf field <code>int32 version = 10;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * The version of current collection schema updates, increment every time the schema content is updating, 
     *
     * Generated from protobuf field <code>int32 version = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * 0 when the collection is created or the collection schema is updated before 2.6.5.
     * the name dbName and description take no effect to it.
     *
     * Generated from protobuf field <code>bool enable_namespace = 15;</code>
     * @return bool
     */
    public function getEnableNamespace()
    {
        return $this->enable_namespace;
    }

    /**
     * 0 when the collection is created or the collection schema is updated before 2.6.5.
     * the name dbName and description take no effect to it.
     *
     * Generated from protobuf field <code>bool enable_namespace = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableNamespace(bool $var)
    {
        $this->enable_namespace = $var;

        return $this;
    }

}

