<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * FieldPartialUpdateOp describes how the values carried by the matching
 * FieldData should be applied against the existing row during a partial
 * upsert.
 * The message is referenced from UpsertRequest.field_ops rather than
 * embedded in FieldData to keep FieldData a pure data carrier — FieldData
 * flows through InsertRequest, QueryResults, SearchResultData and
 * internal msgstream paths where an op directive would be meaningless
 * and risk accidental echo-back on client-side read-modify-write flows.
 * Ops are matched to FieldData entries by field_name. When no op message
 * targets a given field, that field is merged with REPLACE semantics
 * (full overwrite), preserving backward compatibility.
 *
 * Generated from protobuf message <code>milvus.proto.schema.FieldPartialUpdateOp</code>
 */
class FieldPartialUpdateOp extends \Google\Protobuf\Internal\Message
{
    /**
     * field_name identifies the FieldData this op targets. Must match a
     * field carried by UpsertRequest.fields_data; unknown field names are
     * rejected by the server.
     *
     * Generated from protobuf field <code>string field_name = 1;</code>
     */
    protected $field_name = '';
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FieldPartialUpdateOp.OpType op = 2;</code>
     */
    protected $op = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field_name
     *           field_name identifies the FieldData this op targets. Must match a
     *           field carried by UpsertRequest.fields_data; unknown field names are
     *           rejected by the server.
     *     @type int $op
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * field_name identifies the FieldData this op targets. Must match a
     * field carried by UpsertRequest.fields_data; unknown field names are
     * rejected by the server.
     *
     * Generated from protobuf field <code>string field_name = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * field_name identifies the FieldData this op targets. Must match a
     * field carried by UpsertRequest.fields_data; unknown field names are
     * rejected by the server.
     *
     * Generated from protobuf field <code>string field_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->field_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FieldPartialUpdateOp.OpType op = 2;</code>
     * @return int one of the values in {@see \Milvus\Proto\Schema\FieldPartialUpdateOp\OpType}
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FieldPartialUpdateOp.OpType op = 2;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Schema\FieldPartialUpdateOp\OpType}
     * @return $this
     */
    public function setOp(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Schema\FieldPartialUpdateOp\OpType::class);
        $this->op = $var;

        return $this;
    }

}

