<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * \@brief Field schema
 *
 * Generated from protobuf message <code>milvus.proto.schema.FieldSchema</code>
 */
class FieldSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 fieldID = 1;</code>
     */
    protected $fieldID = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>bool is_primary_key = 3;</code>
     */
    protected $is_primary_key = false;
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType data_type = 5;</code>
     */
    protected $data_type = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 6;</code>
     */
    private $type_params;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair index_params = 7;</code>
     */
    private $index_params;
    /**
     * Generated from protobuf field <code>bool autoID = 8;</code>
     */
    protected $autoID = false;
    /**
     * To keep compatible with older version, the default
     *
     * Generated from protobuf field <code>.milvus.proto.schema.FieldState state = 9;</code>
     */
    protected $state = 0;
    /**
     * state is `Created`.
     *
     * Generated from protobuf field <code>.milvus.proto.schema.DataType element_type = 10;</code>
     */
    protected $element_type = 0;
    /**
     * default_value only support scalars except array, json and timestamptz for now
     *
     * Generated from protobuf field <code>.milvus.proto.schema.ValueField default_value = 11;</code>
     */
    protected $default_value = null;
    /**
     * mark whether this field is the dynamic field
     *
     * Generated from protobuf field <code>bool is_dynamic = 12;</code>
     */
    protected $is_dynamic = false;
    /**
     * enable logic partitions
     *
     * Generated from protobuf field <code>bool is_partition_key = 13;</code>
     */
    protected $is_partition_key = false;
    /**
     * Generated from protobuf field <code>bool is_clustering_key = 14;</code>
     */
    protected $is_clustering_key = false;
    /**
     * enable set null as field value
     *
     * Generated from protobuf field <code>bool nullable = 15;</code>
     */
    protected $nullable = false;
    /**
     * Generated from protobuf field <code>bool is_function_output = 16;</code>
     */
    protected $is_function_output = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $fieldID
     *     @type string $name
     *     @type bool $is_primary_key
     *     @type string $description
     *     @type int $data_type
     *     @type \Milvus\Proto\Common\KeyValuePair[] $type_params
     *     @type \Milvus\Proto\Common\KeyValuePair[] $index_params
     *     @type bool $autoID
     *     @type int $state
     *           To keep compatible with older version, the default
     *     @type int $element_type
     *           state is `Created`.
     *     @type \Milvus\Proto\Schema\ValueField $default_value
     *           default_value only support scalars except array, json and timestamptz for now
     *     @type bool $is_dynamic
     *           mark whether this field is the dynamic field
     *     @type bool $is_partition_key
     *           enable logic partitions
     *     @type bool $is_clustering_key
     *     @type bool $nullable
     *           enable set null as field value
     *     @type bool $is_function_output
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 1;</code>
     * @return int|string
     */
    public function getFieldID()
    {
        return $this->fieldID;
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFieldID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->fieldID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_primary_key = 3;</code>
     * @return bool
     */
    public function getIsPrimaryKey()
    {
        return $this->is_primary_key;
    }

    /**
     * Generated from protobuf field <code>bool is_primary_key = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPrimaryKey(bool $var)
    {
        $this->is_primary_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType data_type = 5;</code>
     * @return int one of the values in {@see \Milvus\Proto\Schema\DataType}
     */
    public function getDataType()
    {
        return $this->data_type;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType data_type = 5;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Schema\DataType}
     * @return $this
     */
    public function setDataType(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Schema\DataType::class);
        $this->data_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 6;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getTypeParams()
    {
        return $this->type_params;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 6;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setTypeParams(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->type_params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair index_params = 7;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getIndexParams()
    {
        return $this->index_params;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair index_params = 7;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setIndexParams(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->index_params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool autoID = 8;</code>
     * @return bool
     */
    public function getAutoID()
    {
        return $this->autoID;
    }

    /**
     * Generated from protobuf field <code>bool autoID = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setAutoID(bool $var)
    {
        $this->autoID = $var;

        return $this;
    }

    /**
     * To keep compatible with older version, the default
     *
     * Generated from protobuf field <code>.milvus.proto.schema.FieldState state = 9;</code>
     * @return int one of the values in {@see \Milvus\Proto\Schema\FieldState}
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * To keep compatible with older version, the default
     *
     * Generated from protobuf field <code>.milvus.proto.schema.FieldState state = 9;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Schema\FieldState}
     * @return $this
     */
    public function setState(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Schema\FieldState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * state is `Created`.
     *
     * Generated from protobuf field <code>.milvus.proto.schema.DataType element_type = 10;</code>
     * @return int one of the values in {@see \Milvus\Proto\Schema\DataType}
     */
    public function getElementType()
    {
        return $this->element_type;
    }

    /**
     * state is `Created`.
     *
     * Generated from protobuf field <code>.milvus.proto.schema.DataType element_type = 10;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Schema\DataType}
     * @return $this
     */
    public function setElementType(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Schema\DataType::class);
        $this->element_type = $var;

        return $this;
    }

    /**
     * default_value only support scalars except array, json and timestamptz for now
     *
     * Generated from protobuf field <code>.milvus.proto.schema.ValueField default_value = 11;</code>
     * @return \Milvus\Proto\Schema\ValueField|null
     */
    public function getDefaultValue()
    {
        return $this->default_value;
    }

    public function hasDefaultValue()
    {
        return isset($this->default_value);
    }

    public function clearDefaultValue()
    {
        unset($this->default_value);
    }

    /**
     * default_value only support scalars except array, json and timestamptz for now
     *
     * Generated from protobuf field <code>.milvus.proto.schema.ValueField default_value = 11;</code>
     * @param \Milvus\Proto\Schema\ValueField $var
     * @return $this
     */
    public function setDefaultValue(\Milvus\Proto\Schema\ValueField|null $var)
    {
        $this->default_value = $var;

        return $this;
    }

    /**
     * mark whether this field is the dynamic field
     *
     * Generated from protobuf field <code>bool is_dynamic = 12;</code>
     * @return bool
     */
    public function getIsDynamic()
    {
        return $this->is_dynamic;
    }

    /**
     * mark whether this field is the dynamic field
     *
     * Generated from protobuf field <code>bool is_dynamic = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDynamic(bool $var)
    {
        $this->is_dynamic = $var;

        return $this;
    }

    /**
     * enable logic partitions
     *
     * Generated from protobuf field <code>bool is_partition_key = 13;</code>
     * @return bool
     */
    public function getIsPartitionKey()
    {
        return $this->is_partition_key;
    }

    /**
     * enable logic partitions
     *
     * Generated from protobuf field <code>bool is_partition_key = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPartitionKey(bool $var)
    {
        $this->is_partition_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_clustering_key = 14;</code>
     * @return bool
     */
    public function getIsClusteringKey()
    {
        return $this->is_clustering_key;
    }

    /**
     * Generated from protobuf field <code>bool is_clustering_key = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsClusteringKey(bool $var)
    {
        $this->is_clustering_key = $var;

        return $this;
    }

    /**
     * enable set null as field value
     *
     * Generated from protobuf field <code>bool nullable = 15;</code>
     * @return bool
     */
    public function getNullable()
    {
        return $this->nullable;
    }

    /**
     * enable set null as field value
     *
     * Generated from protobuf field <code>bool nullable = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setNullable(bool $var)
    {
        $this->nullable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_function_output = 16;</code>
     * @return bool
     */
    public function getIsFunctionOutput()
    {
        return $this->is_function_output;
    }

    /**
     * Generated from protobuf field <code>bool is_function_output = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFunctionOutput(bool $var)
    {
        $this->is_function_output = $var;

        return $this;
    }

}

