<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.schema.FieldData</code>
 */
class FieldData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string field_name = 2;</code>
     */
    protected $field_name = '';
    /**
     * Generated from protobuf field <code>int64 field_id = 5;</code>
     */
    protected $field_id = 0;
    /**
     * Generated from protobuf field <code>bool is_dynamic = 6;</code>
     */
    protected $is_dynamic = false;
    /**
     * Generated from protobuf field <code>repeated bool valid_data = 7;</code>
     */
    private $valid_data;
    protected $field;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $field_name
     *     @type \Milvus\Proto\Schema\ScalarField $scalars
     *     @type \Milvus\Proto\Schema\VectorField $vectors
     *     @type \Milvus\Proto\Schema\StructArrayField $struct_arrays
     *     @type int|string $field_id
     *     @type bool $is_dynamic
     *     @type bool[] $valid_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType type = 1;</code>
     * @return int one of the values in {@see \Milvus\Proto\Schema\DataType}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType type = 1;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Schema\DataType}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Schema\DataType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string field_name = 2;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>string field_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->field_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.ScalarField scalars = 3;</code>
     * @return \Milvus\Proto\Schema\ScalarField|null
     */
    public function getScalars()
    {
        return $this->readOneof(3);
    }

    public function hasScalars()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.ScalarField scalars = 3;</code>
     * @param \Milvus\Proto\Schema\ScalarField $var
     * @return $this
     */
    public function setScalars(\Milvus\Proto\Schema\ScalarField|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.VectorField vectors = 4;</code>
     * @return \Milvus\Proto\Schema\VectorField|null
     */
    public function getVectors()
    {
        return $this->readOneof(4);
    }

    public function hasVectors()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.VectorField vectors = 4;</code>
     * @param \Milvus\Proto\Schema\VectorField $var
     * @return $this
     */
    public function setVectors(\Milvus\Proto\Schema\VectorField|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.StructArrayField struct_arrays = 8;</code>
     * @return \Milvus\Proto\Schema\StructArrayField|null
     */
    public function getStructArrays()
    {
        return $this->readOneof(8);
    }

    public function hasStructArrays()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.StructArrayField struct_arrays = 8;</code>
     * @param \Milvus\Proto\Schema\StructArrayField $var
     * @return $this
     */
    public function setStructArrays(\Milvus\Proto\Schema\StructArrayField|null $var)
    {
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 field_id = 5;</code>
     * @return int|string
     */
    public function getFieldId()
    {
        return $this->field_id;
    }

    /**
     * Generated from protobuf field <code>int64 field_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFieldId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->field_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_dynamic = 6;</code>
     * @return bool
     */
    public function getIsDynamic()
    {
        return $this->is_dynamic;
    }

    /**
     * Generated from protobuf field <code>bool is_dynamic = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDynamic(bool $var)
    {
        $this->is_dynamic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bool valid_data = 7;</code>
     * @return RepeatedField<bool>
     */
    public function getValidData()
    {
        return $this->valid_data;
    }

    /**
     * Generated from protobuf field <code>repeated bool valid_data = 7;</code>
     * @param bool[] $var
     * @return $this
     */
    public function setValidData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->valid_data = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getField()
    {
        return $this->whichOneof("field");
    }

}

