<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.schema.FunctionSchema</code>
 */
class FunctionSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int64 id = 2;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FunctionType type = 4;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>repeated string input_field_names = 5;</code>
     */
    private $input_field_names;
    /**
     * Generated from protobuf field <code>repeated int64 input_field_ids = 6;</code>
     */
    private $input_field_ids;
    /**
     * Generated from protobuf field <code>repeated string output_field_names = 7;</code>
     */
    private $output_field_names;
    /**
     * Generated from protobuf field <code>repeated int64 output_field_ids = 8;</code>
     */
    private $output_field_ids;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair params = 9;</code>
     */
    private $params;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int|string $id
     *     @type string $description
     *     @type int $type
     *     @type string[] $input_field_names
     *     @type int[]|string[] $input_field_ids
     *     @type string[] $output_field_names
     *     @type int[]|string[] $output_field_ids
     *     @type \Milvus\Proto\Common\KeyValuePair[] $params
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 id = 2;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FunctionType type = 4;</code>
     * @return int one of the values in {@see \Milvus\Proto\Schema\FunctionType}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FunctionType type = 4;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Schema\FunctionType}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Schema\FunctionType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string input_field_names = 5;</code>
     * @return RepeatedField<string>
     */
    public function getInputFieldNames()
    {
        return $this->input_field_names;
    }

    /**
     * Generated from protobuf field <code>repeated string input_field_names = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setInputFieldNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->input_field_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 input_field_ids = 6;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getInputFieldIds()
    {
        return $this->input_field_ids;
    }

    /**
     * Generated from protobuf field <code>repeated int64 input_field_ids = 6;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setInputFieldIds(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->input_field_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string output_field_names = 7;</code>
     * @return RepeatedField<string>
     */
    public function getOutputFieldNames()
    {
        return $this->output_field_names;
    }

    /**
     * Generated from protobuf field <code>repeated string output_field_names = 7;</code>
     * @param string[] $var
     * @return $this
     */
    public function setOutputFieldNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->output_field_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 output_field_ids = 8;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getOutputFieldIds()
    {
        return $this->output_field_ids;
    }

    /**
     * Generated from protobuf field <code>repeated int64 output_field_ids = 8;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setOutputFieldIds(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->output_field_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair params = 9;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair params = 9;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setParams(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->params = $arr;

        return $this;
    }

}

