<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.schema.IDs</code>
 */
class IDs extends \Google\Protobuf\Internal\Message
{
    protected $id_field;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Schema\LongArray $int_id
     *     @type \Milvus\Proto\Schema\StringArray $str_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.LongArray int_id = 1;</code>
     * @return \Milvus\Proto\Schema\LongArray|null
     */
    public function getIntId()
    {
        return $this->readOneof(1);
    }

    public function hasIntId()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.LongArray int_id = 1;</code>
     * @param \Milvus\Proto\Schema\LongArray $var
     * @return $this
     */
    public function setIntId(\Milvus\Proto\Schema\LongArray|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.StringArray str_id = 2;</code>
     * @return \Milvus\Proto\Schema\StringArray|null
     */
    public function getStrId()
    {
        return $this->readOneof(2);
    }

    public function hasStrId()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.StringArray str_id = 2;</code>
     * @param \Milvus\Proto\Schema\StringArray $var
     * @return $this
     */
    public function setStrId(\Milvus\Proto\Schema\StringArray|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getIdField()
    {
        return $this->whichOneof("id_field");
    }

}

