<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * MetricValue is the typed result of a single metric aggregation.
 *
 * Generated from protobuf message <code>milvus.proto.schema.MetricValue</code>
 */
class MetricValue extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $int_val
     *     @type float $double_val
     *     @type string $string_val
     *     @type bool $bool_val
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 int_val = 1;</code>
     * @return int|string
     */
    public function getIntVal()
    {
        return $this->readOneof(1);
    }

    public function hasIntVal()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>int64 int_val = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntVal(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_val = 2;</code>
     * @return float
     */
    public function getDoubleVal()
    {
        return $this->readOneof(2);
    }

    public function hasDoubleVal()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>double double_val = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleVal(float $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_val = 3;</code>
     * @return string
     */
    public function getStringVal()
    {
        return $this->readOneof(3);
    }

    public function hasStringVal()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>string string_val = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStringVal(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool_val = 4;</code>
     * @return bool
     */
    public function getBoolVal()
    {
        return $this->readOneof(4);
    }

    public function hasBoolVal()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>bool bool_val = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolVal(bool $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

