<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.schema.ScalarField</code>
 */
class ScalarField extends \Google\Protobuf\Internal\Message
{
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Schema\BoolArray $bool_data
     *     @type \Milvus\Proto\Schema\IntArray $int_data
     *     @type \Milvus\Proto\Schema\LongArray $long_data
     *     @type \Milvus\Proto\Schema\FloatArray $float_data
     *     @type \Milvus\Proto\Schema\DoubleArray $double_data
     *     @type \Milvus\Proto\Schema\StringArray $string_data
     *     @type \Milvus\Proto\Schema\BytesArray $bytes_data
     *     @type \Milvus\Proto\Schema\ArrayArray $array_data
     *     @type \Milvus\Proto\Schema\JSONArray $json_data
     *     @type \Milvus\Proto\Schema\GeometryArray $geometry_data
     *     @type \Milvus\Proto\Schema\TimestamptzArray $timestamptz_data
     *     @type \Milvus\Proto\Schema\GeometryWktArray $geometry_wkt_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.BoolArray bool_data = 1;</code>
     * @return \Milvus\Proto\Schema\BoolArray|null
     */
    public function getBoolData()
    {
        return $this->readOneof(1);
    }

    public function hasBoolData()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.BoolArray bool_data = 1;</code>
     * @param \Milvus\Proto\Schema\BoolArray $var
     * @return $this
     */
    public function setBoolData(\Milvus\Proto\Schema\BoolArray|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IntArray int_data = 2;</code>
     * @return \Milvus\Proto\Schema\IntArray|null
     */
    public function getIntData()
    {
        return $this->readOneof(2);
    }

    public function hasIntData()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IntArray int_data = 2;</code>
     * @param \Milvus\Proto\Schema\IntArray $var
     * @return $this
     */
    public function setIntData(\Milvus\Proto\Schema\IntArray|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.LongArray long_data = 3;</code>
     * @return \Milvus\Proto\Schema\LongArray|null
     */
    public function getLongData()
    {
        return $this->readOneof(3);
    }

    public function hasLongData()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.LongArray long_data = 3;</code>
     * @param \Milvus\Proto\Schema\LongArray $var
     * @return $this
     */
    public function setLongData(\Milvus\Proto\Schema\LongArray|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FloatArray float_data = 4;</code>
     * @return \Milvus\Proto\Schema\FloatArray|null
     */
    public function getFloatData()
    {
        return $this->readOneof(4);
    }

    public function hasFloatData()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FloatArray float_data = 4;</code>
     * @param \Milvus\Proto\Schema\FloatArray $var
     * @return $this
     */
    public function setFloatData(\Milvus\Proto\Schema\FloatArray|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DoubleArray double_data = 5;</code>
     * @return \Milvus\Proto\Schema\DoubleArray|null
     */
    public function getDoubleData()
    {
        return $this->readOneof(5);
    }

    public function hasDoubleData()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DoubleArray double_data = 5;</code>
     * @param \Milvus\Proto\Schema\DoubleArray $var
     * @return $this
     */
    public function setDoubleData(\Milvus\Proto\Schema\DoubleArray|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.StringArray string_data = 6;</code>
     * @return \Milvus\Proto\Schema\StringArray|null
     */
    public function getStringData()
    {
        return $this->readOneof(6);
    }

    public function hasStringData()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.StringArray string_data = 6;</code>
     * @param \Milvus\Proto\Schema\StringArray $var
     * @return $this
     */
    public function setStringData(\Milvus\Proto\Schema\StringArray|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.BytesArray bytes_data = 7;</code>
     * @return \Milvus\Proto\Schema\BytesArray|null
     */
    public function getBytesData()
    {
        return $this->readOneof(7);
    }

    public function hasBytesData()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.BytesArray bytes_data = 7;</code>
     * @param \Milvus\Proto\Schema\BytesArray $var
     * @return $this
     */
    public function setBytesData(\Milvus\Proto\Schema\BytesArray|null $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.ArrayArray array_data = 8;</code>
     * @return \Milvus\Proto\Schema\ArrayArray|null
     */
    public function getArrayData()
    {
        return $this->readOneof(8);
    }

    public function hasArrayData()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.ArrayArray array_data = 8;</code>
     * @param \Milvus\Proto\Schema\ArrayArray $var
     * @return $this
     */
    public function setArrayData(\Milvus\Proto\Schema\ArrayArray|null $var)
    {
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.JSONArray json_data = 9;</code>
     * @return \Milvus\Proto\Schema\JSONArray|null
     */
    public function getJsonData()
    {
        return $this->readOneof(9);
    }

    public function hasJsonData()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.JSONArray json_data = 9;</code>
     * @param \Milvus\Proto\Schema\JSONArray $var
     * @return $this
     */
    public function setJsonData(\Milvus\Proto\Schema\JSONArray|null $var)
    {
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.GeometryArray geometry_data = 10;</code>
     * @return \Milvus\Proto\Schema\GeometryArray|null
     */
    public function getGeometryData()
    {
        return $this->readOneof(10);
    }

    public function hasGeometryData()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.GeometryArray geometry_data = 10;</code>
     * @param \Milvus\Proto\Schema\GeometryArray $var
     * @return $this
     */
    public function setGeometryData(\Milvus\Proto\Schema\GeometryArray|null $var)
    {
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.TimestamptzArray timestamptz_data = 11;</code>
     * @return \Milvus\Proto\Schema\TimestamptzArray|null
     */
    public function getTimestamptzData()
    {
        return $this->readOneof(11);
    }

    public function hasTimestamptzData()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.TimestamptzArray timestamptz_data = 11;</code>
     * @param \Milvus\Proto\Schema\TimestamptzArray $var
     * @return $this
     */
    public function setTimestamptzData(\Milvus\Proto\Schema\TimestamptzArray|null $var)
    {
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.GeometryWktArray geometry_wkt_data = 12;</code>
     * @return \Milvus\Proto\Schema\GeometryWktArray|null
     */
    public function getGeometryWktData()
    {
        return $this->readOneof(12);
    }

    public function hasGeometryWktData()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.GeometryWktArray geometry_wkt_data = 12;</code>
     * @param \Milvus\Proto\Schema\GeometryWktArray $var
     * @return $this
     */
    public function setGeometryWktData(\Milvus\Proto\Schema\GeometryWktArray|null $var)
    {
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

