<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.schema.SearchResultData</code>
 */
class SearchResultData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 num_queries = 1;</code>
     */
    protected $num_queries = 0;
    /**
     * Generated from protobuf field <code>int64 top_k = 2;</code>
     */
    protected $top_k = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 3;</code>
     */
    private $fields_data;
    /**
     * Generated from protobuf field <code>repeated float scores = 4;</code>
     */
    private $scores;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 5;</code>
     */
    protected $ids = null;
    /**
     * Generated from protobuf field <code>repeated int64 topks = 6;</code>
     */
    private $topks;
    /**
     * Generated from protobuf field <code>repeated string output_fields = 7;</code>
     */
    private $output_fields;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FieldData group_by_field_value = 8;</code>
     */
    protected $group_by_field_value = null;
    /**
     * Generated from protobuf field <code>int64 all_search_count = 9;</code>
     */
    protected $all_search_count = 0;
    /**
     * Generated from protobuf field <code>repeated float distances = 10;</code>
     */
    private $distances;
    /**
     * Generated from protobuf field <code>optional .milvus.proto.schema.SearchIteratorV2Results search_iterator_v2_results = 11;</code>
     */
    protected $search_iterator_v2_results = null;
    /**
     * Generated from protobuf field <code>repeated float recalls = 12;</code>
     */
    private $recalls;
    /**
     * Generated from protobuf field <code>string primary_field_name = 13;</code>
     */
    protected $primary_field_name = '';
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.HighlightResult highlight_results = 14;</code>
     */
    private $highlight_results;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.LongArray element_indices = 15;</code>
     */
    protected $element_indices = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $num_queries
     *     @type int|string $top_k
     *     @type \Milvus\Proto\Schema\FieldData[] $fields_data
     *     @type float[] $scores
     *     @type \Milvus\Proto\Schema\IDs $ids
     *     @type int[]|string[] $topks
     *     @type string[] $output_fields
     *     @type \Milvus\Proto\Schema\FieldData $group_by_field_value
     *     @type int|string $all_search_count
     *     @type float[] $distances
     *     @type \Milvus\Proto\Schema\SearchIteratorV2Results $search_iterator_v2_results
     *     @type float[] $recalls
     *     @type string $primary_field_name
     *     @type \Milvus\Proto\Common\HighlightResult[] $highlight_results
     *     @type \Milvus\Proto\Schema\LongArray $element_indices
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 num_queries = 1;</code>
     * @return int|string
     */
    public function getNumQueries()
    {
        return $this->num_queries;
    }

    /**
     * Generated from protobuf field <code>int64 num_queries = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumQueries(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->num_queries = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 top_k = 2;</code>
     * @return int|string
     */
    public function getTopK()
    {
        return $this->top_k;
    }

    /**
     * Generated from protobuf field <code>int64 top_k = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTopK(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->top_k = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 3;</code>
     * @return RepeatedField<\Milvus\Proto\Schema\FieldData>
     */
    public function getFieldsData()
    {
        return $this->fields_data;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 3;</code>
     * @param \Milvus\Proto\Schema\FieldData[] $var
     * @return $this
     */
    public function setFieldsData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldData::class);
        $this->fields_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float scores = 4;</code>
     * @return RepeatedField<float>
     */
    public function getScores()
    {
        return $this->scores;
    }

    /**
     * Generated from protobuf field <code>repeated float scores = 4;</code>
     * @param float[] $var
     * @return $this
     */
    public function setScores(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->scores = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 5;</code>
     * @return \Milvus\Proto\Schema\IDs|null
     */
    public function getIds()
    {
        return $this->ids;
    }

    public function hasIds()
    {
        return isset($this->ids);
    }

    public function clearIds()
    {
        unset($this->ids);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 5;</code>
     * @param \Milvus\Proto\Schema\IDs $var
     * @return $this
     */
    public function setIds(\Milvus\Proto\Schema\IDs|null $var)
    {
        $this->ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 topks = 6;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getTopks()
    {
        return $this->topks;
    }

    /**
     * Generated from protobuf field <code>repeated int64 topks = 6;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setTopks(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->topks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string output_fields = 7;</code>
     * @return RepeatedField<string>
     */
    public function getOutputFields()
    {
        return $this->output_fields;
    }

    /**
     * Generated from protobuf field <code>repeated string output_fields = 7;</code>
     * @param string[] $var
     * @return $this
     */
    public function setOutputFields(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->output_fields = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FieldData group_by_field_value = 8;</code>
     * @return \Milvus\Proto\Schema\FieldData|null
     */
    public function getGroupByFieldValue()
    {
        return $this->group_by_field_value;
    }

    public function hasGroupByFieldValue()
    {
        return isset($this->group_by_field_value);
    }

    public function clearGroupByFieldValue()
    {
        unset($this->group_by_field_value);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FieldData group_by_field_value = 8;</code>
     * @param \Milvus\Proto\Schema\FieldData $var
     * @return $this
     */
    public function setGroupByFieldValue(\Milvus\Proto\Schema\FieldData|null $var)
    {
        $this->group_by_field_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 all_search_count = 9;</code>
     * @return int|string
     */
    public function getAllSearchCount()
    {
        return $this->all_search_count;
    }

    /**
     * Generated from protobuf field <code>int64 all_search_count = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAllSearchCount(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->all_search_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float distances = 10;</code>
     * @return RepeatedField<float>
     */
    public function getDistances()
    {
        return $this->distances;
    }

    /**
     * Generated from protobuf field <code>repeated float distances = 10;</code>
     * @param float[] $var
     * @return $this
     */
    public function setDistances(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->distances = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .milvus.proto.schema.SearchIteratorV2Results search_iterator_v2_results = 11;</code>
     * @return \Milvus\Proto\Schema\SearchIteratorV2Results|null
     */
    public function getSearchIteratorV2Results()
    {
        return $this->search_iterator_v2_results;
    }

    public function hasSearchIteratorV2Results()
    {
        return isset($this->search_iterator_v2_results);
    }

    public function clearSearchIteratorV2Results()
    {
        unset($this->search_iterator_v2_results);
    }

    /**
     * Generated from protobuf field <code>optional .milvus.proto.schema.SearchIteratorV2Results search_iterator_v2_results = 11;</code>
     * @param \Milvus\Proto\Schema\SearchIteratorV2Results $var
     * @return $this
     */
    public function setSearchIteratorV2Results(\Milvus\Proto\Schema\SearchIteratorV2Results|null $var)
    {
        $this->search_iterator_v2_results = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float recalls = 12;</code>
     * @return RepeatedField<float>
     */
    public function getRecalls()
    {
        return $this->recalls;
    }

    /**
     * Generated from protobuf field <code>repeated float recalls = 12;</code>
     * @param float[] $var
     * @return $this
     */
    public function setRecalls(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->recalls = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string primary_field_name = 13;</code>
     * @return string
     */
    public function getPrimaryFieldName()
    {
        return $this->primary_field_name;
    }

    /**
     * Generated from protobuf field <code>string primary_field_name = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setPrimaryFieldName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->primary_field_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.HighlightResult highlight_results = 14;</code>
     * @return RepeatedField<\Milvus\Proto\Common\HighlightResult>
     */
    public function getHighlightResults()
    {
        return $this->highlight_results;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.HighlightResult highlight_results = 14;</code>
     * @param \Milvus\Proto\Common\HighlightResult[] $var
     * @return $this
     */
    public function setHighlightResults(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\HighlightResult::class);
        $this->highlight_results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.LongArray element_indices = 15;</code>
     * @return \Milvus\Proto\Schema\LongArray|null
     */
    public function getElementIndices()
    {
        return $this->element_indices;
    }

    public function hasElementIndices()
    {
        return isset($this->element_indices);
    }

    public function clearElementIndices()
    {
        unset($this->element_indices);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.LongArray element_indices = 15;</code>
     * @param \Milvus\Proto\Schema\LongArray $var
     * @return $this
     */
    public function setElementIndices(\Milvus\Proto\Schema\LongArray|null $var)
    {
        $this->element_indices = $var;

        return $this;
    }

}

