<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.schema.StructArrayFieldSchema</code>
 */
class StructArrayFieldSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 fieldID = 1;</code>
     */
    protected $fieldID = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldSchema fields = 4;</code>
     */
    private $fields;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 5;</code>
     */
    private $type_params;
    /**
     * Generated from protobuf field <code>bool nullable = 6;</code>
     */
    protected $nullable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $fieldID
     *     @type string $name
     *     @type string $description
     *     @type \Milvus\Proto\Schema\FieldSchema[] $fields
     *     @type \Milvus\Proto\Common\KeyValuePair[] $type_params
     *     @type bool $nullable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 1;</code>
     * @return int|string
     */
    public function getFieldID()
    {
        return $this->fieldID;
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFieldID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->fieldID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldSchema fields = 4;</code>
     * @return RepeatedField<\Milvus\Proto\Schema\FieldSchema>
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldSchema fields = 4;</code>
     * @param \Milvus\Proto\Schema\FieldSchema[] $var
     * @return $this
     */
    public function setFields(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldSchema::class);
        $this->fields = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 5;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getTypeParams()
    {
        return $this->type_params;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 5;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setTypeParams(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->type_params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool nullable = 6;</code>
     * @return bool
     */
    public function getNullable()
    {
        return $this->nullable;
    }

    /**
     * Generated from protobuf field <code>bool nullable = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setNullable(bool $var)
    {
        $this->nullable = $var;

        return $this;
    }

}

