<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.schema.VectorField</code>
 */
class VectorField extends \Google\Protobuf\Internal\Message
{
    /**
     * For sparse vector, dim is the max dimension of the current batch of vectors
     *
     * Generated from protobuf field <code>int64 dim = 1;</code>
     */
    protected $dim = 0;
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $dim
     *           For sparse vector, dim is the max dimension of the current batch of vectors
     *     @type \Milvus\Proto\Schema\FloatArray $float_vector
     *     @type string $binary_vector
     *     @type string $float16_vector
     *     @type string $bfloat16_vector
     *     @type \Milvus\Proto\Schema\SparseFloatArray $sparse_float_vector
     *     @type string $int8_vector
     *     @type \Milvus\Proto\Schema\VectorArray $vector_array
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * For sparse vector, dim is the max dimension of the current batch of vectors
     *
     * Generated from protobuf field <code>int64 dim = 1;</code>
     * @return int|string
     */
    public function getDim()
    {
        return $this->dim;
    }

    /**
     * For sparse vector, dim is the max dimension of the current batch of vectors
     *
     * Generated from protobuf field <code>int64 dim = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDim(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->dim = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FloatArray float_vector = 2;</code>
     * @return \Milvus\Proto\Schema\FloatArray|null
     */
    public function getFloatVector()
    {
        return $this->readOneof(2);
    }

    public function hasFloatVector()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FloatArray float_vector = 2;</code>
     * @param \Milvus\Proto\Schema\FloatArray $var
     * @return $this
     */
    public function setFloatVector(\Milvus\Proto\Schema\FloatArray|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes binary_vector = 3;</code>
     * @return string
     */
    public function getBinaryVector()
    {
        return $this->readOneof(3);
    }

    public function hasBinaryVector()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>bytes binary_vector = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBinaryVector(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes float16_vector = 4;</code>
     * @return string
     */
    public function getFloat16Vector()
    {
        return $this->readOneof(4);
    }

    public function hasFloat16Vector()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>bytes float16_vector = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFloat16Vector(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bfloat16_vector = 5;</code>
     * @return string
     */
    public function getBfloat16Vector()
    {
        return $this->readOneof(5);
    }

    public function hasBfloat16Vector()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>bytes bfloat16_vector = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBfloat16Vector(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.SparseFloatArray sparse_float_vector = 6;</code>
     * @return \Milvus\Proto\Schema\SparseFloatArray|null
     */
    public function getSparseFloatVector()
    {
        return $this->readOneof(6);
    }

    public function hasSparseFloatVector()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.SparseFloatArray sparse_float_vector = 6;</code>
     * @param \Milvus\Proto\Schema\SparseFloatArray $var
     * @return $this
     */
    public function setSparseFloatVector(\Milvus\Proto\Schema\SparseFloatArray|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes int8_vector = 7;</code>
     * @return string
     */
    public function getInt8Vector()
    {
        return $this->readOneof(7);
    }

    public function hasInt8Vector()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>bytes int8_vector = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setInt8Vector(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.VectorArray vector_array = 8;</code>
     * @return \Milvus\Proto\Schema\VectorArray|null
     */
    public function getVectorArray()
    {
        return $this->readOneof(8);
    }

    public function hasVectorArray()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.VectorArray vector_array = 8;</code>
     * @param \Milvus\Proto\Schema\VectorArray $var
     * @return $this
     */
    public function setVectorArray(\Milvus\Proto\Schema\VectorArray|null $var)
    {
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

