<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.AnalyzerToken</code>
 */
class AnalyzerToken extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string token = 1;</code>
     */
    protected $token = '';
    /**
     * Generated from protobuf field <code>int64 start_offset = 2;</code>
     */
    protected $start_offset = 0;
    /**
     * Generated from protobuf field <code>int64 end_offset = 3;</code>
     */
    protected $end_offset = 0;
    /**
     * Generated from protobuf field <code>int64 position = 4;</code>
     */
    protected $position = 0;
    /**
     * Generated from protobuf field <code>int64 position_length = 5;</code>
     */
    protected $position_length = 0;
    /**
     * Generated from protobuf field <code>uint32 hash = 6;</code>
     */
    protected $hash = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *     @type int|string $start_offset
     *     @type int|string $end_offset
     *     @type int|string $position
     *     @type int|string $position_length
     *     @type int $hash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 start_offset = 2;</code>
     * @return int|string
     */
    public function getStartOffset()
    {
        return $this->start_offset;
    }

    /**
     * Generated from protobuf field <code>int64 start_offset = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartOffset(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->start_offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 end_offset = 3;</code>
     * @return int|string
     */
    public function getEndOffset()
    {
        return $this->end_offset;
    }

    /**
     * Generated from protobuf field <code>int64 end_offset = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndOffset(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->end_offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 position = 4;</code>
     * @return int|string
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Generated from protobuf field <code>int64 position = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPosition(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 position_length = 5;</code>
     * @return int|string
     */
    public function getPositionLength()
    {
        return $this->position_length;
    }

    /**
     * Generated from protobuf field <code>int64 position_length = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPositionLength(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->position_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 hash = 6;</code>
     * @return int
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>uint32 hash = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setHash(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->hash = $var;

        return $this;
    }

}

