<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.CalcDistanceResults</code>
 */
class CalcDistanceResults extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    protected $array;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *     @type \Milvus\Proto\Schema\IntArray $int_dist
     *     @type \Milvus\Proto\Schema\FloatArray $float_dist
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus(\Milvus\Proto\Common\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IntArray int_dist = 2;</code>
     * @return \Milvus\Proto\Schema\IntArray|null
     */
    public function getIntDist()
    {
        return $this->readOneof(2);
    }

    public function hasIntDist()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IntArray int_dist = 2;</code>
     * @param \Milvus\Proto\Schema\IntArray $var
     * @return $this
     */
    public function setIntDist(\Milvus\Proto\Schema\IntArray|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FloatArray float_dist = 3;</code>
     * @return \Milvus\Proto\Schema\FloatArray|null
     */
    public function getFloatDist()
    {
        return $this->readOneof(3);
    }

    public function hasFloatDist()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FloatArray float_dist = 3;</code>
     * @param \Milvus\Proto\Schema\FloatArray $var
     * @return $this
     */
    public function setFloatDist(\Milvus\Proto\Schema\FloatArray|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getArray()
    {
        return $this->whichOneof("array");
    }

}

