<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ClientTelemetry</code>
 */
class ClientTelemetry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ClientInfo client_info = 1;</code>
     */
    protected $client_info = null;
    /**
     * Generated from protobuf field <code>int64 last_heartbeat_time = 2;</code>
     */
    protected $last_heartbeat_time = 0;
    /**
     * Generated from protobuf field <code>string status = 3;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>repeated string databases = 4;</code>
     */
    private $databases;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.OperationMetrics metrics = 5;</code>
     */
    private $metrics;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\ClientInfo $client_info
     *     @type int|string $last_heartbeat_time
     *     @type string $status
     *     @type string[] $databases
     *     @type \Milvus\Proto\Common\OperationMetrics[] $metrics
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ClientInfo client_info = 1;</code>
     * @return \Milvus\Proto\Common\ClientInfo|null
     */
    public function getClientInfo()
    {
        return $this->client_info;
    }

    public function hasClientInfo()
    {
        return isset($this->client_info);
    }

    public function clearClientInfo()
    {
        unset($this->client_info);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ClientInfo client_info = 1;</code>
     * @param \Milvus\Proto\Common\ClientInfo $var
     * @return $this
     */
    public function setClientInfo(\Milvus\Proto\Common\ClientInfo|null $var)
    {
        $this->client_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 last_heartbeat_time = 2;</code>
     * @return int|string
     */
    public function getLastHeartbeatTime()
    {
        return $this->last_heartbeat_time;
    }

    /**
     * Generated from protobuf field <code>int64 last_heartbeat_time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastHeartbeatTime(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->last_heartbeat_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string databases = 4;</code>
     * @return RepeatedField<string>
     */
    public function getDatabases()
    {
        return $this->databases;
    }

    /**
     * Generated from protobuf field <code>repeated string databases = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDatabases(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->databases = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.OperationMetrics metrics = 5;</code>
     * @return RepeatedField<\Milvus\Proto\Common\OperationMetrics>
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.OperationMetrics metrics = 5;</code>
     * @param \Milvus\Proto\Common\OperationMetrics[] $var
     * @return $this
     */
    public function setMetrics(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\OperationMetrics::class);
        $this->metrics = $arr;

        return $this;
    }

}

