<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ComputePhraseMatchSlopRequest</code>
 */
class ComputePhraseMatchSlopRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string analyzer_params = 2;</code>
     */
    protected $analyzer_params = '';
    /**
     * Generated from protobuf field <code>string query_text = 3;</code>
     */
    protected $query_text = '';
    /**
     * Generated from protobuf field <code>repeated string data_texts = 4;</code>
     */
    private $data_texts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $analyzer_params
     *     @type string $query_text
     *     @type string[] $data_texts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string analyzer_params = 2;</code>
     * @return string
     */
    public function getAnalyzerParams()
    {
        return $this->analyzer_params;
    }

    /**
     * Generated from protobuf field <code>string analyzer_params = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAnalyzerParams(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->analyzer_params = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string query_text = 3;</code>
     * @return string
     */
    public function getQueryText()
    {
        return $this->query_text;
    }

    /**
     * Generated from protobuf field <code>string query_text = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryText(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->query_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string data_texts = 4;</code>
     * @return RepeatedField<string>
     */
    public function getDataTexts()
    {
        return $this->data_texts;
    }

    /**
     * Generated from protobuf field <code>repeated string data_texts = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDataTexts(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->data_texts = $arr;

        return $this;
    }

}

