<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ConnectResponse</code>
 */
class ConnectResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ServerInfo server_info = 2;</code>
     */
    protected $server_info = null;
    /**
     * Generated from protobuf field <code>int64 identifier = 3;</code>
     */
    protected $identifier = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *     @type \Milvus\Proto\Common\ServerInfo $server_info
     *     @type int|string $identifier
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus(\Milvus\Proto\Common\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ServerInfo server_info = 2;</code>
     * @return \Milvus\Proto\Common\ServerInfo|null
     */
    public function getServerInfo()
    {
        return $this->server_info;
    }

    public function hasServerInfo()
    {
        return isset($this->server_info);
    }

    public function clearServerInfo()
    {
        unset($this->server_info);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ServerInfo server_info = 2;</code>
     * @param \Milvus\Proto\Common\ServerInfo $var
     * @return $this
     */
    public function setServerInfo(\Milvus\Proto\Common\ServerInfo|null $var)
    {
        $this->server_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 identifier = 3;</code>
     * @return int|string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Generated from protobuf field <code>int64 identifier = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIdentifier(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->identifier = $var;

        return $this;
    }

}

