<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.CreateResourceGroupRequest</code>
 */
class CreateResourceGroupRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string resource_group = 2;</code>
     */
    protected $resource_group = '';
    /**
     * Generated from protobuf field <code>.milvus.proto.rg.ResourceGroupConfig config = 3;</code>
     */
    protected $config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $resource_group
     *     @type \Milvus\Proto\Rg\ResourceGroupConfig $config
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string resource_group = 2;</code>
     * @return string
     */
    public function getResourceGroup()
    {
        return $this->resource_group;
    }

    /**
     * Generated from protobuf field <code>string resource_group = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceGroup(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->resource_group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.rg.ResourceGroupConfig config = 3;</code>
     * @return \Milvus\Proto\Rg\ResourceGroupConfig|null
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function hasConfig()
    {
        return isset($this->config);
    }

    public function clearConfig()
    {
        unset($this->config);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.rg.ResourceGroupConfig config = 3;</code>
     * @param \Milvus\Proto\Rg\ResourceGroupConfig $var
     * @return $this
     */
    public function setConfig(\Milvus\Proto\Rg\ResourceGroupConfig|null $var)
    {
        $this->config = $var;

        return $this;
    }

}

