<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Row Policy Management
 *
 * Generated from protobuf message <code>milvus.proto.milvus.CreateRowPolicyRequest</code>
 */
class CreateRowPolicyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     */
    protected $collection_name = '';
    /**
     * Generated from protobuf field <code>string policy_name = 4;</code>
     */
    protected $policy_name = '';
    /**
     * actions this policy controls
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.RowPolicyAction actions = 5;</code>
     */
    private $actions;
    /**
     * role names that this policy applies to
     *
     * Generated from protobuf field <code>repeated string roles = 6;</code>
     */
    private $roles;
    /**
     * expression for filtering data during queries
     *
     * Generated from protobuf field <code>string using_expr = 7;</code>
     */
    protected $using_expr = '';
    /**
     * expression for validating data during mutations
     *
     * Generated from protobuf field <code>string check_expr = 8;</code>
     */
    protected $check_expr = '';
    /**
     * optional description
     *
     * Generated from protobuf field <code>string description = 9;</code>
     */
    protected $description = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $db_name
     *     @type string $collection_name
     *     @type string $policy_name
     *     @type int[] $actions
     *           actions this policy controls
     *     @type string[] $roles
     *           role names that this policy applies to
     *     @type string $using_expr
     *           expression for filtering data during queries
     *     @type string $check_expr
     *           expression for validating data during mutations
     *     @type string $description
     *           optional description
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string policy_name = 4;</code>
     * @return string
     */
    public function getPolicyName()
    {
        return $this->policy_name;
    }

    /**
     * Generated from protobuf field <code>string policy_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPolicyName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->policy_name = $var;

        return $this;
    }

    /**
     * actions this policy controls
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.RowPolicyAction actions = 5;</code>
     * @return RepeatedField<int> one of the values in {@see \Milvus\Proto\Milvus\RowPolicyAction}
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * actions this policy controls
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.RowPolicyAction actions = 5;</code>
     * @param int[] $var one of the values in {@see \Milvus\Proto\Milvus\RowPolicyAction}
     * @return $this
     */
    public function setActions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Milvus\Proto\Milvus\RowPolicyAction::class);
        $this->actions = $arr;

        return $this;
    }

    /**
     * role names that this policy applies to
     *
     * Generated from protobuf field <code>repeated string roles = 6;</code>
     * @return RepeatedField<string>
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * role names that this policy applies to
     *
     * Generated from protobuf field <code>repeated string roles = 6;</code>
     * @param string[] $var
     * @return $this
     */
    public function setRoles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->roles = $arr;

        return $this;
    }

    /**
     * expression for filtering data during queries
     *
     * Generated from protobuf field <code>string using_expr = 7;</code>
     * @return string
     */
    public function getUsingExpr()
    {
        return $this->using_expr;
    }

    /**
     * expression for filtering data during queries
     *
     * Generated from protobuf field <code>string using_expr = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUsingExpr(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->using_expr = $var;

        return $this;
    }

    /**
     * expression for validating data during mutations
     *
     * Generated from protobuf field <code>string check_expr = 8;</code>
     * @return string
     */
    public function getCheckExpr()
    {
        return $this->check_expr;
    }

    /**
     * expression for validating data during mutations
     *
     * Generated from protobuf field <code>string check_expr = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCheckExpr(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->check_expr = $var;

        return $this;
    }

    /**
     * optional description
     *
     * Generated from protobuf field <code>string description = 9;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * optional description
     *
     * Generated from protobuf field <code>string description = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

}

