<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.DescribeSnapshotResponse</code>
 */
class DescribeSnapshotResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * user-defined snapshot name
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * user-defined snapshot description
     *
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * collection name
     *
     * Generated from protobuf field <code>string collection_name = 4;</code>
     */
    protected $collection_name = '';
    /**
     * the partition names in the snapshot.
     *
     * Generated from protobuf field <code>repeated string partition_names = 5;</code>
     */
    private $partition_names;
    /**
     * create timestamp, all stream data before this timestamp will be flushed to segment list.
     *
     * Generated from protobuf field <code>int64 create_ts = 6;</code>
     */
    protected $create_ts = 0;
    /**
     * s3 location of the snapshot meta file if snapshot is exported to s3.
     *
     * Generated from protobuf field <code>string s3_location = 7;</code>
     */
    protected $s3_location = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *     @type string $name
     *           user-defined snapshot name
     *     @type string $description
     *           user-defined snapshot description
     *     @type string $collection_name
     *           collection name
     *     @type string[] $partition_names
     *           the partition names in the snapshot.
     *     @type int|string $create_ts
     *           create timestamp, all stream data before this timestamp will be flushed to segment list.
     *     @type string $s3_location
     *           s3 location of the snapshot meta file if snapshot is exported to s3.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus(\Milvus\Proto\Common\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * user-defined snapshot name
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * user-defined snapshot name
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * user-defined snapshot description
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * user-defined snapshot description
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

    /**
     * collection name
     *
     * Generated from protobuf field <code>string collection_name = 4;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * collection name
     *
     * Generated from protobuf field <code>string collection_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * the partition names in the snapshot.
     *
     * Generated from protobuf field <code>repeated string partition_names = 5;</code>
     * @return RepeatedField<string>
     */
    public function getPartitionNames()
    {
        return $this->partition_names;
    }

    /**
     * the partition names in the snapshot.
     *
     * Generated from protobuf field <code>repeated string partition_names = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPartitionNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->partition_names = $arr;

        return $this;
    }

    /**
     * create timestamp, all stream data before this timestamp will be flushed to segment list.
     *
     * Generated from protobuf field <code>int64 create_ts = 6;</code>
     * @return int|string
     */
    public function getCreateTs()
    {
        return $this->create_ts;
    }

    /**
     * create timestamp, all stream data before this timestamp will be flushed to segment list.
     *
     * Generated from protobuf field <code>int64 create_ts = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTs(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->create_ts = $var;

        return $this;
    }

    /**
     * s3 location of the snapshot meta file if snapshot is exported to s3.
     *
     * Generated from protobuf field <code>string s3_location = 7;</code>
     * @return string
     */
    public function getS3Location()
    {
        return $this->s3_location;
    }

    /**
     * s3 location of the snapshot meta file if snapshot is exported to s3.
     *
     * Generated from protobuf field <code>string s3_location = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setS3Location(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->s3_location = $var;

        return $this;
    }

}

