<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * DescribeCollection Response
 *
 * Generated from protobuf message <code>milvus.proto.milvus.DescribeCollectionResponse</code>
 */
class DescribeCollectionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Contain error_code and reason
     *
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * The schema param when you created collection.
     *
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 2;</code>
     */
    protected $schema = null;
    /**
     * The collection id
     *
     * Generated from protobuf field <code>int64 collectionID = 3;</code>
     */
    protected $collectionID = 0;
    /**
     * System design related, users should not perceive
     *
     * Generated from protobuf field <code>repeated string virtual_channel_names = 4;</code>
     */
    private $virtual_channel_names;
    /**
     * System design related, users should not perceive
     *
     * Generated from protobuf field <code>repeated string physical_channel_names = 5;</code>
     */
    private $physical_channel_names;
    /**
     * Hybrid timestamp in milvus
     *
     * Generated from protobuf field <code>uint64 created_timestamp = 6;</code>
     */
    protected $created_timestamp = 0;
    /**
     * The utc timestamp calculated by created_timestamp
     *
     * Generated from protobuf field <code>uint64 created_utc_timestamp = 7;</code>
     */
    protected $created_utc_timestamp = 0;
    /**
     * The shards number you set.
     *
     * Generated from protobuf field <code>int32 shards_num = 8;</code>
     */
    protected $shards_num = 0;
    /**
     * The aliases of this collection
     *
     * Generated from protobuf field <code>repeated string aliases = 9;</code>
     */
    private $aliases;
    /**
     * The message ID/posititon when collection is created
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyDataPair start_positions = 10;</code>
     */
    private $start_positions;
    /**
     * The consistency level that the collection used, modification is not supported now.
     *
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
     */
    protected $consistency_level = 0;
    /**
     * The collection name
     *
     * Generated from protobuf field <code>string collection_name = 12;</code>
     */
    protected $collection_name = '';
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair properties = 13;</code>
     */
    private $properties;
    /**
     * Generated from protobuf field <code>string db_name = 14;</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>int64 num_partitions = 15;</code>
     */
    protected $num_partitions = 0;
    /**
     * Generated from protobuf field <code>int64 db_id = 16;</code>
     */
    protected $db_id = 0;
    /**
     * Generated from protobuf field <code>uint64 request_time = 17;</code>
     */
    protected $request_time = 0;
    /**
     * Generated from protobuf field <code>uint64 update_timestamp = 18;</code>
     */
    protected $update_timestamp = 0;
    /**
     * Generated from protobuf field <code>string update_timestamp_str = 19;</code>
     */
    protected $update_timestamp_str = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *           Contain error_code and reason
     *     @type \Milvus\Proto\Schema\CollectionSchema $schema
     *           The schema param when you created collection.
     *     @type int|string $collectionID
     *           The collection id
     *     @type string[] $virtual_channel_names
     *           System design related, users should not perceive
     *     @type string[] $physical_channel_names
     *           System design related, users should not perceive
     *     @type int|string $created_timestamp
     *           Hybrid timestamp in milvus
     *     @type int|string $created_utc_timestamp
     *           The utc timestamp calculated by created_timestamp
     *     @type int $shards_num
     *           The shards number you set.
     *     @type string[] $aliases
     *           The aliases of this collection
     *     @type \Milvus\Proto\Common\KeyDataPair[] $start_positions
     *           The message ID/posititon when collection is created
     *     @type int $consistency_level
     *           The consistency level that the collection used, modification is not supported now.
     *     @type string $collection_name
     *           The collection name
     *     @type \Milvus\Proto\Common\KeyValuePair[] $properties
     *     @type string $db_name
     *     @type int|string $num_partitions
     *     @type int|string $db_id
     *     @type int|string $request_time
     *     @type int|string $update_timestamp
     *     @type string $update_timestamp_str
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Contain error_code and reason
     *
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Contain error_code and reason
     *
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus(\Milvus\Proto\Common\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * The schema param when you created collection.
     *
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 2;</code>
     * @return \Milvus\Proto\Schema\CollectionSchema|null
     */
    public function getSchema()
    {
        return $this->schema;
    }

    public function hasSchema()
    {
        return isset($this->schema);
    }

    public function clearSchema()
    {
        unset($this->schema);
    }

    /**
     * The schema param when you created collection.
     *
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 2;</code>
     * @param \Milvus\Proto\Schema\CollectionSchema $var
     * @return $this
     */
    public function setSchema(\Milvus\Proto\Schema\CollectionSchema|null $var)
    {
        $this->schema = $var;

        return $this;
    }

    /**
     * The collection id
     *
     * Generated from protobuf field <code>int64 collectionID = 3;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * The collection id
     *
     * Generated from protobuf field <code>int64 collectionID = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * System design related, users should not perceive
     *
     * Generated from protobuf field <code>repeated string virtual_channel_names = 4;</code>
     * @return RepeatedField<string>
     */
    public function getVirtualChannelNames()
    {
        return $this->virtual_channel_names;
    }

    /**
     * System design related, users should not perceive
     *
     * Generated from protobuf field <code>repeated string virtual_channel_names = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setVirtualChannelNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->virtual_channel_names = $arr;

        return $this;
    }

    /**
     * System design related, users should not perceive
     *
     * Generated from protobuf field <code>repeated string physical_channel_names = 5;</code>
     * @return RepeatedField<string>
     */
    public function getPhysicalChannelNames()
    {
        return $this->physical_channel_names;
    }

    /**
     * System design related, users should not perceive
     *
     * Generated from protobuf field <code>repeated string physical_channel_names = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPhysicalChannelNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->physical_channel_names = $arr;

        return $this;
    }

    /**
     * Hybrid timestamp in milvus
     *
     * Generated from protobuf field <code>uint64 created_timestamp = 6;</code>
     * @return int|string
     */
    public function getCreatedTimestamp()
    {
        return $this->created_timestamp;
    }

    /**
     * Hybrid timestamp in milvus
     *
     * Generated from protobuf field <code>uint64 created_timestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->created_timestamp = $var;

        return $this;
    }

    /**
     * The utc timestamp calculated by created_timestamp
     *
     * Generated from protobuf field <code>uint64 created_utc_timestamp = 7;</code>
     * @return int|string
     */
    public function getCreatedUtcTimestamp()
    {
        return $this->created_utc_timestamp;
    }

    /**
     * The utc timestamp calculated by created_timestamp
     *
     * Generated from protobuf field <code>uint64 created_utc_timestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedUtcTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->created_utc_timestamp = $var;

        return $this;
    }

    /**
     * The shards number you set.
     *
     * Generated from protobuf field <code>int32 shards_num = 8;</code>
     * @return int
     */
    public function getShardsNum()
    {
        return $this->shards_num;
    }

    /**
     * The shards number you set.
     *
     * Generated from protobuf field <code>int32 shards_num = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setShardsNum(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->shards_num = $var;

        return $this;
    }

    /**
     * The aliases of this collection
     *
     * Generated from protobuf field <code>repeated string aliases = 9;</code>
     * @return RepeatedField<string>
     */
    public function getAliases()
    {
        return $this->aliases;
    }

    /**
     * The aliases of this collection
     *
     * Generated from protobuf field <code>repeated string aliases = 9;</code>
     * @param string[] $var
     * @return $this
     */
    public function setAliases(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->aliases = $arr;

        return $this;
    }

    /**
     * The message ID/posititon when collection is created
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyDataPair start_positions = 10;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyDataPair>
     */
    public function getStartPositions()
    {
        return $this->start_positions;
    }

    /**
     * The message ID/posititon when collection is created
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyDataPair start_positions = 10;</code>
     * @param \Milvus\Proto\Common\KeyDataPair[] $var
     * @return $this
     */
    public function setStartPositions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyDataPair::class);
        $this->start_positions = $arr;

        return $this;
    }

    /**
     * The consistency level that the collection used, modification is not supported now.
     *
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
     * @return int one of the values in {@see \Milvus\Proto\Common\ConsistencyLevel}
     */
    public function getConsistencyLevel()
    {
        return $this->consistency_level;
    }

    /**
     * The consistency level that the collection used, modification is not supported now.
     *
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Common\ConsistencyLevel}
     * @return $this
     */
    public function setConsistencyLevel(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\ConsistencyLevel::class);
        $this->consistency_level = $var;

        return $this;
    }

    /**
     * The collection name
     *
     * Generated from protobuf field <code>string collection_name = 12;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * The collection name
     *
     * Generated from protobuf field <code>string collection_name = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair properties = 13;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair properties = 13;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 14;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 num_partitions = 15;</code>
     * @return int|string
     */
    public function getNumPartitions()
    {
        return $this->num_partitions;
    }

    /**
     * Generated from protobuf field <code>int64 num_partitions = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumPartitions(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->num_partitions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 db_id = 16;</code>
     * @return int|string
     */
    public function getDbId()
    {
        return $this->db_id;
    }

    /**
     * Generated from protobuf field <code>int64 db_id = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDbId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->db_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 request_time = 17;</code>
     * @return int|string
     */
    public function getRequestTime()
    {
        return $this->request_time;
    }

    /**
     * Generated from protobuf field <code>uint64 request_time = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequestTime(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->request_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 update_timestamp = 18;</code>
     * @return int|string
     */
    public function getUpdateTimestamp()
    {
        return $this->update_timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 update_timestamp = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->update_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string update_timestamp_str = 19;</code>
     * @return string
     */
    public function getUpdateTimestampStr()
    {
        return $this->update_timestamp_str;
    }

    /**
     * Generated from protobuf field <code>string update_timestamp_str = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateTimestampStr(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->update_timestamp_str = $var;

        return $this;
    }

}

