<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.FlushAllResponse</code>
 */
class FlushAllResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>uint64 flush_all_ts = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $flush_all_ts = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.FlushAllResult flush_results = 3 [deprecated = true];</code>
     * @deprecated
     */
    private $flush_results;
    /**
     * pchannel -> FlushAllMsg
     *
     * Generated from protobuf field <code>map<string, .milvus.proto.common.ImmutableMessage> flush_all_msgs = 4;</code>
     */
    private $flush_all_msgs;
    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.ClusterInfo cluster_info = 5;</code>
     */
    protected $cluster_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *     @type int|string $flush_all_ts
     *     @type \Milvus\Proto\Milvus\FlushAllResult[] $flush_results
     *     @type array|\Google\Protobuf\Internal\MapField $flush_all_msgs
     *           pchannel -> FlushAllMsg
     *     @type \Milvus\Proto\Milvus\ClusterInfo $cluster_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus(\Milvus\Proto\Common\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 flush_all_ts = 2 [deprecated = true];</code>
     * @return int|string
     * @deprecated
     */
    public function getFlushAllTs()
    {
        if ($this->flush_all_ts !== 0) {
            @trigger_error('flush_all_ts is deprecated.', E_USER_DEPRECATED);
        }
        return $this->flush_all_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 flush_all_ts = 2 [deprecated = true];</code>
     * @param int|string $var
     * @return $this
     * @deprecated
     */
    public function setFlushAllTs(int|string $var)
    {
        @trigger_error('flush_all_ts is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkUint64($var);
        $this->flush_all_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.FlushAllResult flush_results = 3 [deprecated = true];</code>
     * @return RepeatedField<\Milvus\Proto\Milvus\FlushAllResult>
     * @deprecated
     */
    public function getFlushResults()
    {
        if (count($this->flush_results) !== 0) {
            @trigger_error('flush_results is deprecated.', E_USER_DEPRECATED);
        }
        return $this->flush_results;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.FlushAllResult flush_results = 3 [deprecated = true];</code>
     * @param \Milvus\Proto\Milvus\FlushAllResult[] $var
     * @return $this
     * @deprecated
     */
    public function setFlushResults(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\FlushAllResult::class);
        if (count($arr) !== 0) {
            @trigger_error('flush_results is deprecated.', E_USER_DEPRECATED);
        }
        $this->flush_results = $arr;

        return $this;
    }

    /**
     * pchannel -> FlushAllMsg
     *
     * Generated from protobuf field <code>map<string, .milvus.proto.common.ImmutableMessage> flush_all_msgs = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFlushAllMsgs()
    {
        return $this->flush_all_msgs;
    }

    /**
     * pchannel -> FlushAllMsg
     *
     * Generated from protobuf field <code>map<string, .milvus.proto.common.ImmutableMessage> flush_all_msgs = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFlushAllMsgs(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\ImmutableMessage::class);
        $this->flush_all_msgs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.ClusterInfo cluster_info = 5;</code>
     * @return \Milvus\Proto\Milvus\ClusterInfo|null
     */
    public function getClusterInfo()
    {
        return $this->cluster_info;
    }

    public function hasClusterInfo()
    {
        return isset($this->cluster_info);
    }

    public function clearClusterInfo()
    {
        unset($this->cluster_info);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.ClusterInfo cluster_info = 5;</code>
     * @param \Milvus\Proto\Milvus\ClusterInfo $var
     * @return $this
     */
    public function setClusterInfo(\Milvus\Proto\Milvus\ClusterInfo|null $var)
    {
        $this->cluster_info = $var;

        return $this;
    }

}

