<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Deprecated
 *
 * Generated from protobuf message <code>milvus.proto.milvus.FlushAllState</code>
 */
class FlushAllState extends \Google\Protobuf\Internal\Message
{
    /**
     * Database name for this flush state report
     *
     * Generated from protobuf field <code>string db_name = 1;</code>
     */
    protected $db_name = '';
    /**
     * Collection-level flush state mapping
     * Key: collection name, Value: true if collection is fully flushed
     *
     * Generated from protobuf field <code>map<string, bool> collection_flush_states = 2;</code>
     */
    private $collection_flush_states;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $db_name
     *           Database name for this flush state report
     *     @type array|\Google\Protobuf\Internal\MapField $collection_flush_states
     *           Collection-level flush state mapping
     *           Key: collection name, Value: true if collection is fully flushed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Database name for this flush state report
     *
     * Generated from protobuf field <code>string db_name = 1;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Database name for this flush state report
     *
     * Generated from protobuf field <code>string db_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Collection-level flush state mapping
     * Key: collection name, Value: true if collection is fully flushed
     *
     * Generated from protobuf field <code>map<string, bool> collection_flush_states = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCollectionFlushStates()
    {
        return $this->collection_flush_states;
    }

    /**
     * Collection-level flush state mapping
     * Key: collection name, Value: true if collection is fully flushed
     *
     * Generated from protobuf field <code>map<string, bool> collection_flush_states = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCollectionFlushStates(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->collection_flush_states = $arr;

        return $this;
    }

}

