<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.GetClientTelemetryResponse</code>
 */
class GetClientTelemetryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.ClientTelemetry clients = 2;</code>
     */
    private $clients;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Metrics aggregated = 3;</code>
     */
    protected $aggregated = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *     @type \Milvus\Proto\Milvus\ClientTelemetry[] $clients
     *     @type \Milvus\Proto\Common\Metrics $aggregated
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus(\Milvus\Proto\Common\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.ClientTelemetry clients = 2;</code>
     * @return RepeatedField<\Milvus\Proto\Milvus\ClientTelemetry>
     */
    public function getClients()
    {
        return $this->clients;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.ClientTelemetry clients = 2;</code>
     * @param \Milvus\Proto\Milvus\ClientTelemetry[] $var
     * @return $this
     */
    public function setClients(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\ClientTelemetry::class);
        $this->clients = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Metrics aggregated = 3;</code>
     * @return \Milvus\Proto\Common\Metrics|null
     */
    public function getAggregated()
    {
        return $this->aggregated;
    }

    public function hasAggregated()
    {
        return isset($this->aggregated);
    }

    public function clearAggregated()
    {
        unset($this->aggregated);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Metrics aggregated = 3;</code>
     * @param \Milvus\Proto\Common\Metrics $var
     * @return $this
     */
    public function setAggregated(\Milvus\Proto\Common\Metrics|null $var)
    {
        $this->aggregated = $var;

        return $this;
    }

}

