<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Get Client Telemetry
 *
 * Generated from protobuf message <code>milvus.proto.milvus.GetClientTelemetryRequest</code>
 */
class GetClientTelemetryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string database = 1;</code>
     */
    protected $database = '';
    /**
     * Generated from protobuf field <code>string client_id = 2;</code>
     */
    protected $client_id = '';
    /**
     * Generated from protobuf field <code>bool include_metrics = 3;</code>
     */
    protected $include_metrics = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $database
     *     @type string $client_id
     *     @type bool $include_metrics
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string database = 1;</code>
     * @return string
     */
    public function getDatabase()
    {
        return $this->database;
    }

    /**
     * Generated from protobuf field <code>string database = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDatabase(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->database = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_id = 2;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>string client_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool include_metrics = 3;</code>
     * @return bool
     */
    public function getIncludeMetrics()
    {
        return $this->include_metrics;
    }

    /**
     * Generated from protobuf field <code>bool include_metrics = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeMetrics(bool $var)
    {
        $this->include_metrics = $var;

        return $this;
    }

}

