<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.GetRefreshExternalCollectionProgressResponse</code>
 */
class GetRefreshExternalCollectionProgressResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.RefreshExternalCollectionJobInfo job_info = 2;</code>
     */
    protected $job_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *     @type \Milvus\Proto\Milvus\RefreshExternalCollectionJobInfo $job_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus(\Milvus\Proto\Common\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.RefreshExternalCollectionJobInfo job_info = 2;</code>
     * @return \Milvus\Proto\Milvus\RefreshExternalCollectionJobInfo|null
     */
    public function getJobInfo()
    {
        return $this->job_info;
    }

    public function hasJobInfo()
    {
        return isset($this->job_info);
    }

    public function clearJobInfo()
    {
        unset($this->job_info);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.RefreshExternalCollectionJobInfo job_info = 2;</code>
     * @param \Milvus\Proto\Milvus\RefreshExternalCollectionJobInfo $var
     * @return $this
     */
    public function setJobInfo(\Milvus\Proto\Milvus\RefreshExternalCollectionJobInfo|null $var)
    {
        $this->job_info = $var;

        return $this;
    }

}

