<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * Will return statistics in stats field like [{key:"row_count",value:"1"}]
 * WARNING: This API is experimental and not useful for now.
 *
 * Generated from protobuf message <code>milvus.proto.milvus.GetStatisticsResponse</code>
 */
class GetStatisticsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Contain error_code and reason
     *
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Collection statistics data
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair stats = 2;</code>
     */
    private $stats;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *           Contain error_code and reason
     *     @type \Milvus\Proto\Common\KeyValuePair[] $stats
     *           Collection statistics data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Contain error_code and reason
     *
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Contain error_code and reason
     *
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus(\Milvus\Proto\Common\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * Collection statistics data
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair stats = 2;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * Collection statistics data
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair stats = 2;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setStats(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->stats = $arr;

        return $this;
    }

}

