<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.Hits</code>
 */
class Hits extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 IDs = 1;</code>
     */
    private $IDs;
    /**
     * Generated from protobuf field <code>repeated bytes row_data = 2;</code>
     */
    private $row_data;
    /**
     * Generated from protobuf field <code>repeated float scores = 3;</code>
     */
    private $scores;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[] $IDs
     *     @type string[] $row_data
     *     @type float[] $scores
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int64 IDs = 1;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getIDs()
    {
        return $this->IDs;
    }

    /**
     * Generated from protobuf field <code>repeated int64 IDs = 1;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setIDs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->IDs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes row_data = 2;</code>
     * @return RepeatedField<string>
     */
    public function getRowData()
    {
        return $this->row_data;
    }

    /**
     * Generated from protobuf field <code>repeated bytes row_data = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setRowData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->row_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float scores = 3;</code>
     * @return RepeatedField<float>
     */
    public function getScores()
    {
        return $this->scores;
    }

    /**
     * Generated from protobuf field <code>repeated float scores = 3;</code>
     * @param float[] $var
     * @return $this
     */
    public function setScores(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->scores = $arr;

        return $this;
    }

}

