<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.HybridSearchRequest</code>
 */
class HybridSearchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * must
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     */
    protected $collection_name = '';
    /**
     * must
     *
     * Generated from protobuf field <code>repeated string partition_names = 4;</code>
     */
    private $partition_names;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
     */
    private $requests;
    /**
     * must
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
     */
    private $rank_params;
    /**
     * Generated from protobuf field <code>uint64 travel_timestamp = 7;</code>
     */
    protected $travel_timestamp = 0;
    /**
     * guarantee_timestamp
     *
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 8;</code>
     */
    protected $guarantee_timestamp = 0;
    /**
     * Generated from protobuf field <code>bool not_return_all_meta = 9;</code>
     */
    protected $not_return_all_meta = false;
    /**
     * Generated from protobuf field <code>repeated string output_fields = 10;</code>
     */
    private $output_fields;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
     */
    protected $consistency_level = 0;
    /**
     * Generated from protobuf field <code>bool use_default_consistency = 12;</code>
     */
    protected $use_default_consistency = false;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FunctionScore function_score = 13;</code>
     */
    protected $function_score = null;
    /**
     * Generated from protobuf field <code>optional string namespace = 14;</code>
     */
    protected $namespace = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *           must
     *     @type string $db_name
     *     @type string $collection_name
     *           must
     *     @type string[] $partition_names
     *           must
     *     @type \Milvus\Proto\Milvus\SearchRequest[] $requests
     *     @type \Milvus\Proto\Common\KeyValuePair[] $rank_params
     *           must
     *     @type int|string $travel_timestamp
     *     @type int|string $guarantee_timestamp
     *           guarantee_timestamp
     *     @type bool $not_return_all_meta
     *     @type string[] $output_fields
     *     @type int $consistency_level
     *     @type bool $use_default_consistency
     *     @type \Milvus\Proto\Schema\FunctionScore $function_score
     *     @type string $namespace
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated string partition_names = 4;</code>
     * @return RepeatedField<string>
     */
    public function getPartitionNames()
    {
        return $this->partition_names;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated string partition_names = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPartitionNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->partition_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
     * @return RepeatedField<\Milvus\Proto\Milvus\SearchRequest>
     */
    public function getRequests()
    {
        return $this->requests;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.SearchRequest requests = 5;</code>
     * @param \Milvus\Proto\Milvus\SearchRequest[] $var
     * @return $this
     */
    public function setRequests(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\SearchRequest::class);
        $this->requests = $arr;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getRankParams()
    {
        return $this->rank_params;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair rank_params = 6;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setRankParams(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->rank_params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 travel_timestamp = 7;</code>
     * @return int|string
     */
    public function getTravelTimestamp()
    {
        return $this->travel_timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 travel_timestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTravelTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->travel_timestamp = $var;

        return $this;
    }

    /**
     * guarantee_timestamp
     *
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 8;</code>
     * @return int|string
     */
    public function getGuaranteeTimestamp()
    {
        return $this->guarantee_timestamp;
    }

    /**
     * guarantee_timestamp
     *
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGuaranteeTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->guarantee_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool not_return_all_meta = 9;</code>
     * @return bool
     */
    public function getNotReturnAllMeta()
    {
        return $this->not_return_all_meta;
    }

    /**
     * Generated from protobuf field <code>bool not_return_all_meta = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setNotReturnAllMeta(bool $var)
    {
        $this->not_return_all_meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string output_fields = 10;</code>
     * @return RepeatedField<string>
     */
    public function getOutputFields()
    {
        return $this->output_fields;
    }

    /**
     * Generated from protobuf field <code>repeated string output_fields = 10;</code>
     * @param string[] $var
     * @return $this
     */
    public function setOutputFields(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->output_fields = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
     * @return int one of the values in {@see \Milvus\Proto\Common\ConsistencyLevel}
     */
    public function getConsistencyLevel()
    {
        return $this->consistency_level;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 11;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Common\ConsistencyLevel}
     * @return $this
     */
    public function setConsistencyLevel(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\ConsistencyLevel::class);
        $this->consistency_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_default_consistency = 12;</code>
     * @return bool
     */
    public function getUseDefaultConsistency()
    {
        return $this->use_default_consistency;
    }

    /**
     * Generated from protobuf field <code>bool use_default_consistency = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseDefaultConsistency(bool $var)
    {
        $this->use_default_consistency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FunctionScore function_score = 13;</code>
     * @return \Milvus\Proto\Schema\FunctionScore|null
     */
    public function getFunctionScore()
    {
        return $this->function_score;
    }

    public function hasFunctionScore()
    {
        return isset($this->function_score);
    }

    public function clearFunctionScore()
    {
        unset($this->function_score);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FunctionScore function_score = 13;</code>
     * @param \Milvus\Proto\Schema\FunctionScore $var
     * @return $this
     */
    public function setFunctionScore(\Milvus\Proto\Schema\FunctionScore|null $var)
    {
        $this->function_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string namespace = 14;</code>
     * @return string
     */
    public function getNamespace()
    {
        return isset($this->namespace) ? $this->namespace : '';
    }

    public function hasNamespace()
    {
        return isset($this->namespace);
    }

    public function clearNamespace()
    {
        unset($this->namespace);
    }

    /**
     * Generated from protobuf field <code>optional string namespace = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

}

