<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ImportRequest</code>
 */
class ImportRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * target collection
     *
     * Generated from protobuf field <code>string collection_name = 1;</code>
     */
    protected $collection_name = '';
    /**
     * target partition
     *
     * Generated from protobuf field <code>string partition_name = 2;</code>
     */
    protected $partition_name = '';
    /**
     * channel names for the collection
     *
     * Generated from protobuf field <code>repeated string channel_names = 3;</code>
     */
    private $channel_names;
    /**
     * the file is row-based or column-based
     *
     * Generated from protobuf field <code>bool row_based = 4;</code>
     */
    protected $row_based = false;
    /**
     * file paths to be imported
     *
     * Generated from protobuf field <code>repeated string files = 5;</code>
     */
    private $files;
    /**
     * import options, bucket, etc.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair options = 6;</code>
     */
    private $options;
    /**
     * target database
     *
     * Generated from protobuf field <code>string db_name = 7;</code>
     */
    protected $db_name = '';
    /**
     * serialized `schema.ClusteringInfo`
     *
     * Generated from protobuf field <code>bytes clustering_info = 8;</code>
     */
    protected $clustering_info = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection_name
     *           target collection
     *     @type string $partition_name
     *           target partition
     *     @type string[] $channel_names
     *           channel names for the collection
     *     @type bool $row_based
     *           the file is row-based or column-based
     *     @type string[] $files
     *           file paths to be imported
     *     @type \Milvus\Proto\Common\KeyValuePair[] $options
     *           import options, bucket, etc.
     *     @type string $db_name
     *           target database
     *     @type string $clustering_info
     *           serialized `schema.ClusteringInfo`
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * target collection
     *
     * Generated from protobuf field <code>string collection_name = 1;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * target collection
     *
     * Generated from protobuf field <code>string collection_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * target partition
     *
     * Generated from protobuf field <code>string partition_name = 2;</code>
     * @return string
     */
    public function getPartitionName()
    {
        return $this->partition_name;
    }

    /**
     * target partition
     *
     * Generated from protobuf field <code>string partition_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPartitionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->partition_name = $var;

        return $this;
    }

    /**
     * channel names for the collection
     *
     * Generated from protobuf field <code>repeated string channel_names = 3;</code>
     * @return RepeatedField<string>
     */
    public function getChannelNames()
    {
        return $this->channel_names;
    }

    /**
     * channel names for the collection
     *
     * Generated from protobuf field <code>repeated string channel_names = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setChannelNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->channel_names = $arr;

        return $this;
    }

    /**
     * the file is row-based or column-based
     *
     * Generated from protobuf field <code>bool row_based = 4;</code>
     * @return bool
     */
    public function getRowBased()
    {
        return $this->row_based;
    }

    /**
     * the file is row-based or column-based
     *
     * Generated from protobuf field <code>bool row_based = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRowBased(bool $var)
    {
        $this->row_based = $var;

        return $this;
    }

    /**
     * file paths to be imported
     *
     * Generated from protobuf field <code>repeated string files = 5;</code>
     * @return RepeatedField<string>
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * file paths to be imported
     *
     * Generated from protobuf field <code>repeated string files = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setFiles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->files = $arr;

        return $this;
    }

    /**
     * import options, bucket, etc.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair options = 6;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * import options, bucket, etc.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair options = 6;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setOptions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->options = $arr;

        return $this;
    }

    /**
     * target database
     *
     * Generated from protobuf field <code>string db_name = 7;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * target database
     *
     * Generated from protobuf field <code>string db_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * serialized `schema.ClusteringInfo`
     *
     * Generated from protobuf field <code>bytes clustering_info = 8;</code>
     * @return string
     */
    public function getClusteringInfo()
    {
        return $this->clustering_info;
    }

    /**
     * serialized `schema.ClusteringInfo`
     *
     * Generated from protobuf field <code>bytes clustering_info = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setClusteringInfo(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->clustering_info = $var;

        return $this;
    }

}

