<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ListUsersWithTagRequest</code>
 */
class ListUsersWithTagRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string tag_key = 2;</code>
     */
    protected $tag_key = '';
    /**
     * Generated from protobuf field <code>string tag_value = 3;</code>
     */
    protected $tag_value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $tag_key
     *     @type string $tag_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tag_key = 2;</code>
     * @return string
     */
    public function getTagKey()
    {
        return $this->tag_key;
    }

    /**
     * Generated from protobuf field <code>string tag_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTagKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->tag_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tag_value = 3;</code>
     * @return string
     */
    public function getTagValue()
    {
        return $this->tag_value;
    }

    /**
     * Generated from protobuf field <code>string tag_value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTagValue(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->tag_value = $var;

        return $this;
    }

}

