<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Do load balancing operation from src_nodeID to dst_nodeID.
 *
 * Generated from protobuf message <code>milvus.proto.milvus.LoadBalanceRequest</code>
 */
class LoadBalanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>int64 src_nodeID = 2;</code>
     */
    protected $src_nodeID = 0;
    /**
     * Generated from protobuf field <code>repeated int64 dst_nodeIDs = 3;</code>
     */
    private $dst_nodeIDs;
    /**
     * Generated from protobuf field <code>repeated int64 sealed_segmentIDs = 4;</code>
     */
    private $sealed_segmentIDs;
    /**
     * Generated from protobuf field <code>string collectionName = 5;</code>
     */
    protected $collectionName = '';
    /**
     * Generated from protobuf field <code>string db_name = 6;</code>
     */
    protected $db_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type int|string $src_nodeID
     *     @type int[]|string[] $dst_nodeIDs
     *     @type int[]|string[] $sealed_segmentIDs
     *     @type string $collectionName
     *     @type string $db_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 src_nodeID = 2;</code>
     * @return int|string
     */
    public function getSrcNodeID()
    {
        return $this->src_nodeID;
    }

    /**
     * Generated from protobuf field <code>int64 src_nodeID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSrcNodeID(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->src_nodeID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 dst_nodeIDs = 3;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getDstNodeIDs()
    {
        return $this->dst_nodeIDs;
    }

    /**
     * Generated from protobuf field <code>repeated int64 dst_nodeIDs = 3;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setDstNodeIDs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->dst_nodeIDs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 sealed_segmentIDs = 4;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getSealedSegmentIDs()
    {
        return $this->sealed_segmentIDs;
    }

    /**
     * Generated from protobuf field <code>repeated int64 sealed_segmentIDs = 4;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setSealedSegmentIDs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->sealed_segmentIDs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collectionName = 5;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collectionName;
    }

    /**
     * Generated from protobuf field <code>string collectionName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collectionName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 6;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

}

