<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 **
 * Load collection data into query nodes, then you can do vector search on this collection.
 *
 * Generated from protobuf message <code>milvus.proto.milvus.LoadCollectionRequest</code>
 */
class LoadCollectionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * The collection name you want to load
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     */
    protected $collection_name = '';
    /**
     * The replica number to load, default by 1
     *
     * Generated from protobuf field <code>int32 replica_number = 4;</code>
     */
    protected $replica_number = 0;
    /**
     * create replica used resource group
     *
     * Generated from protobuf field <code>repeated string resource_groups = 5;</code>
     */
    private $resource_groups;
    /**
     * Whether to enable refresh mode.
     *
     * Generated from protobuf field <code>bool refresh = 6;</code>
     */
    protected $refresh = false;
    /**
     * Field Partial Load fields list
     *
     * Generated from protobuf field <code>repeated string load_fields = 7;</code>
     */
    private $load_fields;
    /**
     * Field Partial load skip load dynamic fields 
     *
     * Generated from protobuf field <code>bool skip_load_dynamic_field = 8;</code>
     */
    protected $skip_load_dynamic_field = false;
    /**
     * Additional parameters for load
     *
     * Generated from protobuf field <code>map<string, string> load_params = 9;</code>
     */
    private $load_params;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *           Not useful for now
     *     @type string $db_name
     *     @type string $collection_name
     *           The collection name you want to load
     *     @type int $replica_number
     *           The replica number to load, default by 1
     *     @type string[] $resource_groups
     *           create replica used resource group
     *     @type bool $refresh
     *           Whether to enable refresh mode.
     *     @type string[] $load_fields
     *           Field Partial Load fields list
     *     @type bool $skip_load_dynamic_field
     *           Field Partial load skip load dynamic fields 
     *     @type array|\Google\Protobuf\Internal\MapField $load_params
     *           Additional parameters for load
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * The collection name you want to load
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * The collection name you want to load
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * The replica number to load, default by 1
     *
     * Generated from protobuf field <code>int32 replica_number = 4;</code>
     * @return int
     */
    public function getReplicaNumber()
    {
        return $this->replica_number;
    }

    /**
     * The replica number to load, default by 1
     *
     * Generated from protobuf field <code>int32 replica_number = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setReplicaNumber(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->replica_number = $var;

        return $this;
    }

    /**
     * create replica used resource group
     *
     * Generated from protobuf field <code>repeated string resource_groups = 5;</code>
     * @return RepeatedField<string>
     */
    public function getResourceGroups()
    {
        return $this->resource_groups;
    }

    /**
     * create replica used resource group
     *
     * Generated from protobuf field <code>repeated string resource_groups = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setResourceGroups(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->resource_groups = $arr;

        return $this;
    }

    /**
     * Whether to enable refresh mode.
     *
     * Generated from protobuf field <code>bool refresh = 6;</code>
     * @return bool
     */
    public function getRefresh()
    {
        return $this->refresh;
    }

    /**
     * Whether to enable refresh mode.
     *
     * Generated from protobuf field <code>bool refresh = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setRefresh(bool $var)
    {
        $this->refresh = $var;

        return $this;
    }

    /**
     * Field Partial Load fields list
     *
     * Generated from protobuf field <code>repeated string load_fields = 7;</code>
     * @return RepeatedField<string>
     */
    public function getLoadFields()
    {
        return $this->load_fields;
    }

    /**
     * Field Partial Load fields list
     *
     * Generated from protobuf field <code>repeated string load_fields = 7;</code>
     * @param string[] $var
     * @return $this
     */
    public function setLoadFields(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->load_fields = $arr;

        return $this;
    }

    /**
     * Field Partial load skip load dynamic fields 
     *
     * Generated from protobuf field <code>bool skip_load_dynamic_field = 8;</code>
     * @return bool
     */
    public function getSkipLoadDynamicField()
    {
        return $this->skip_load_dynamic_field;
    }

    /**
     * Field Partial load skip load dynamic fields 
     *
     * Generated from protobuf field <code>bool skip_load_dynamic_field = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setSkipLoadDynamicField(bool $var)
    {
        $this->skip_load_dynamic_field = $var;

        return $this;
    }

    /**
     * Additional parameters for load
     *
     * Generated from protobuf field <code>map<string, string> load_params = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLoadParams()
    {
        return $this->load_params;
    }

    /**
     * Additional parameters for load
     *
     * Generated from protobuf field <code>map<string, string> load_params = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLoadParams(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->load_params = $arr;

        return $this;
    }

}

