<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.OperatePrivilegeGroupRequest</code>
 */
class OperatePrivilegeGroupRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * group name
     *
     * Generated from protobuf field <code>string group_name = 2;</code>
     */
    protected $group_name = '';
    /**
     * privileges
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.PrivilegeEntity privileges = 3;</code>
     */
    private $privileges;
    /**
     * operation type
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.OperatePrivilegeGroupType type = 4;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *           Not useful for now
     *     @type string $group_name
     *           group name
     *     @type \Milvus\Proto\Milvus\PrivilegeEntity[] $privileges
     *           privileges
     *     @type int $type
     *           operation type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * group name
     *
     * Generated from protobuf field <code>string group_name = 2;</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->group_name;
    }

    /**
     * group name
     *
     * Generated from protobuf field <code>string group_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->group_name = $var;

        return $this;
    }

    /**
     * privileges
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.PrivilegeEntity privileges = 3;</code>
     * @return RepeatedField<\Milvus\Proto\Milvus\PrivilegeEntity>
     */
    public function getPrivileges()
    {
        return $this->privileges;
    }

    /**
     * privileges
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.PrivilegeEntity privileges = 3;</code>
     * @param \Milvus\Proto\Milvus\PrivilegeEntity[] $var
     * @return $this
     */
    public function setPrivileges(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\PrivilegeEntity::class);
        $this->privileges = $arr;

        return $this;
    }

    /**
     * operation type
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.OperatePrivilegeGroupType type = 4;</code>
     * @return int one of the values in {@see \Milvus\Proto\Milvus\OperatePrivilegeGroupType}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * operation type
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.OperatePrivilegeGroupType type = 4;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Milvus\OperatePrivilegeGroupType}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Milvus\OperatePrivilegeGroupType::class);
        $this->type = $var;

        return $this;
    }

}

