<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use UnexpectedValueException;

/**
 * Protobuf type <code>milvus.proto.milvus.OperatePrivilegeGroupType</code>
 */
class OperatePrivilegeGroupType
{
    /**
     * Generated from protobuf enum <code>AddPrivilegesToGroup = 0;</code>
     */
    const AddPrivilegesToGroup = 0;
    /**
     * Generated from protobuf enum <code>RemovePrivilegesFromGroup = 1;</code>
     */
    const RemovePrivilegesFromGroup = 1;

    private static $valueToName = [
        self::AddPrivilegesToGroup => 'AddPrivilegesToGroup',
        self::RemovePrivilegesFromGroup => 'RemovePrivilegesFromGroup',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

