<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.PinSnapshotDataRequest</code>
 */
class PinSnapshotDataRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * snapshot name
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * database name
     *
     * Generated from protobuf field <code>string db_name = 3;</code>
     */
    protected $db_name = '';
    /**
     * collection name
     *
     * Generated from protobuf field <code>string collection_name = 4;</code>
     */
    protected $collection_name = '';
    /**
     * optional: 0 = no expiry, >0 = auto-expire in seconds
     *
     * Generated from protobuf field <code>int64 ttl_seconds = 5;</code>
     */
    protected $ttl_seconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $name
     *           snapshot name
     *     @type string $db_name
     *           database name
     *     @type string $collection_name
     *           collection name
     *     @type int|string $ttl_seconds
     *           optional: 0 = no expiry, >0 = auto-expire in seconds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * snapshot name
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * snapshot name
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * database name
     *
     * Generated from protobuf field <code>string db_name = 3;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * database name
     *
     * Generated from protobuf field <code>string db_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * collection name
     *
     * Generated from protobuf field <code>string collection_name = 4;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * collection name
     *
     * Generated from protobuf field <code>string collection_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * optional: 0 = no expiry, >0 = auto-expire in seconds
     *
     * Generated from protobuf field <code>int64 ttl_seconds = 5;</code>
     * @return int|string
     */
    public function getTtlSeconds()
    {
        return $this->ttl_seconds;
    }

    /**
     * optional: 0 = no expiry, >0 = auto-expire in seconds
     *
     * Generated from protobuf field <code>int64 ttl_seconds = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTtlSeconds(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->ttl_seconds = $var;

        return $this;
    }

}

