<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.QueryCursor</code>
 */
class QueryCursor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 session_ts = 1;</code>
     */
    protected $session_ts = 0;
    protected $cursor_pk;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $session_ts
     *     @type string $str_pk
     *     @type int|string $int_pk
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 session_ts = 1;</code>
     * @return int|string
     */
    public function getSessionTs()
    {
        return $this->session_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 session_ts = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSessionTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->session_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string str_pk = 2;</code>
     * @return string
     */
    public function getStrPk()
    {
        return $this->readOneof(2);
    }

    public function hasStrPk()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>string str_pk = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStrPk(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 int_pk = 3;</code>
     * @return int|string
     */
    public function getIntPk()
    {
        return $this->readOneof(3);
    }

    public function hasIntPk()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>int64 int_pk = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntPk(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getCursorPk()
    {
        return $this->whichOneof("cursor_pk");
    }

}

