<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.QueryResults</code>
 */
class QueryResults extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 2;</code>
     */
    private $fields_data;
    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     */
    protected $collection_name = '';
    /**
     * Generated from protobuf field <code>repeated string output_fields = 4;</code>
     */
    private $output_fields;
    /**
     * for session-like operation like iterator
     *
     * Generated from protobuf field <code>uint64 session_ts = 5;</code>
     */
    protected $session_ts = 0;
    /**
     * Generated from protobuf field <code>string primary_field_name = 6;</code>
     */
    protected $primary_field_name = '';
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.ElementIndices element_indices = 7;</code>
     */
    private $element_indices;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *     @type \Milvus\Proto\Schema\FieldData[] $fields_data
     *     @type string $collection_name
     *     @type string[] $output_fields
     *     @type int|string $session_ts
     *           for session-like operation like iterator
     *     @type string $primary_field_name
     *     @type \Milvus\Proto\Milvus\ElementIndices[] $element_indices
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus(\Milvus\Proto\Common\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 2;</code>
     * @return RepeatedField<\Milvus\Proto\Schema\FieldData>
     */
    public function getFieldsData()
    {
        return $this->fields_data;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 2;</code>
     * @param \Milvus\Proto\Schema\FieldData[] $var
     * @return $this
     */
    public function setFieldsData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldData::class);
        $this->fields_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string output_fields = 4;</code>
     * @return RepeatedField<string>
     */
    public function getOutputFields()
    {
        return $this->output_fields;
    }

    /**
     * Generated from protobuf field <code>repeated string output_fields = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setOutputFields(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->output_fields = $arr;

        return $this;
    }

    /**
     * for session-like operation like iterator
     *
     * Generated from protobuf field <code>uint64 session_ts = 5;</code>
     * @return int|string
     */
    public function getSessionTs()
    {
        return $this->session_ts;
    }

    /**
     * for session-like operation like iterator
     *
     * Generated from protobuf field <code>uint64 session_ts = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSessionTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->session_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string primary_field_name = 6;</code>
     * @return string
     */
    public function getPrimaryFieldName()
    {
        return $this->primary_field_name;
    }

    /**
     * Generated from protobuf field <code>string primary_field_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPrimaryFieldName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->primary_field_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.ElementIndices element_indices = 7;</code>
     * @return RepeatedField<\Milvus\Proto\Milvus\ElementIndices>
     */
    public function getElementIndices()
    {
        return $this->element_indices;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.ElementIndices element_indices = 7;</code>
     * @param \Milvus\Proto\Milvus\ElementIndices[] $var
     * @return $this
     */
    public function setElementIndices(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\ElementIndices::class);
        $this->element_indices = $arr;

        return $this;
    }

}

