<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.RBACMeta</code>
 */
class RBACMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * user
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.UserInfo users = 1;</code>
     */
    private $users;
    /**
     * role
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.RoleEntity roles = 2;</code>
     */
    private $roles;
    /**
     * (role, object, previledge)
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.GrantEntity grants = 3;</code>
     */
    private $grants;
    /**
     * privilege group info
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.PrivilegeGroupInfo privilege_groups = 4;</code>
     */
    private $privilege_groups;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Milvus\UserInfo[] $users
     *           user
     *     @type \Milvus\Proto\Milvus\RoleEntity[] $roles
     *           role
     *     @type \Milvus\Proto\Milvus\GrantEntity[] $grants
     *           (role, object, previledge)
     *     @type \Milvus\Proto\Milvus\PrivilegeGroupInfo[] $privilege_groups
     *           privilege group info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * user
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.UserInfo users = 1;</code>
     * @return RepeatedField<\Milvus\Proto\Milvus\UserInfo>
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * user
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.UserInfo users = 1;</code>
     * @param \Milvus\Proto\Milvus\UserInfo[] $var
     * @return $this
     */
    public function setUsers(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\UserInfo::class);
        $this->users = $arr;

        return $this;
    }

    /**
     * role
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.RoleEntity roles = 2;</code>
     * @return RepeatedField<\Milvus\Proto\Milvus\RoleEntity>
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * role
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.RoleEntity roles = 2;</code>
     * @param \Milvus\Proto\Milvus\RoleEntity[] $var
     * @return $this
     */
    public function setRoles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\RoleEntity::class);
        $this->roles = $arr;

        return $this;
    }

    /**
     * (role, object, previledge)
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.GrantEntity grants = 3;</code>
     * @return RepeatedField<\Milvus\Proto\Milvus\GrantEntity>
     */
    public function getGrants()
    {
        return $this->grants;
    }

    /**
     * (role, object, previledge)
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.GrantEntity grants = 3;</code>
     * @param \Milvus\Proto\Milvus\GrantEntity[] $var
     * @return $this
     */
    public function setGrants(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\GrantEntity::class);
        $this->grants = $arr;

        return $this;
    }

    /**
     * privilege group info
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.PrivilegeGroupInfo privilege_groups = 4;</code>
     * @return RepeatedField<\Milvus\Proto\Milvus\PrivilegeGroupInfo>
     */
    public function getPrivilegeGroups()
    {
        return $this->privilege_groups;
    }

    /**
     * privilege group info
     *
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.PrivilegeGroupInfo privilege_groups = 4;</code>
     * @param \Milvus\Proto\Milvus\PrivilegeGroupInfo[] $var
     * @return $this
     */
    public function setPrivilegeGroups(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\PrivilegeGroupInfo::class);
        $this->privilege_groups = $arr;

        return $this;
    }

}

