<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.RefreshExternalCollectionJobInfo</code>
 */
class RefreshExternalCollectionJobInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Job identifier
     *
     * Generated from protobuf field <code>int64 job_id = 1;</code>
     */
    protected $job_id = 0;
    /**
     * Collection name
     *
     * Generated from protobuf field <code>string collection_name = 2;</code>
     */
    protected $collection_name = '';
    /**
     * Current job state
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.RefreshExternalCollectionState state = 3;</code>
     */
    protected $state = 0;
    /**
     * Progress percentage (0-100)
     *
     * Generated from protobuf field <code>int64 progress = 4;</code>
     */
    protected $progress = 0;
    /**
     * Error message if failed
     *
     * Generated from protobuf field <code>string reason = 5;</code>
     */
    protected $reason = '';
    /**
     * External source used for this job
     *
     * Generated from protobuf field <code>string external_source = 6;</code>
     */
    protected $external_source = '';
    /**
     * Job start timestamp (Unix epoch ms)
     *
     * Generated from protobuf field <code>int64 start_time = 7;</code>
     */
    protected $start_time = 0;
    /**
     * Job end timestamp (0 if not completed)
     *
     * Generated from protobuf field <code>int64 end_time = 8;</code>
     */
    protected $end_time = 0;
    /**
     * External spec used for this job
     *
     * Generated from protobuf field <code>string external_spec = 9;</code>
     */
    protected $external_spec = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $job_id
     *           Job identifier
     *     @type string $collection_name
     *           Collection name
     *     @type int $state
     *           Current job state
     *     @type int|string $progress
     *           Progress percentage (0-100)
     *     @type string $reason
     *           Error message if failed
     *     @type string $external_source
     *           External source used for this job
     *     @type int|string $start_time
     *           Job start timestamp (Unix epoch ms)
     *     @type int|string $end_time
     *           Job end timestamp (0 if not completed)
     *     @type string $external_spec
     *           External spec used for this job
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Job identifier
     *
     * Generated from protobuf field <code>int64 job_id = 1;</code>
     * @return int|string
     */
    public function getJobId()
    {
        return $this->job_id;
    }

    /**
     * Job identifier
     *
     * Generated from protobuf field <code>int64 job_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJobId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->job_id = $var;

        return $this;
    }

    /**
     * Collection name
     *
     * Generated from protobuf field <code>string collection_name = 2;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * Collection name
     *
     * Generated from protobuf field <code>string collection_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * Current job state
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.RefreshExternalCollectionState state = 3;</code>
     * @return int one of the values in {@see \Milvus\Proto\Milvus\RefreshExternalCollectionState}
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Current job state
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.RefreshExternalCollectionState state = 3;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Milvus\RefreshExternalCollectionState}
     * @return $this
     */
    public function setState(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Milvus\RefreshExternalCollectionState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Progress percentage (0-100)
     *
     * Generated from protobuf field <code>int64 progress = 4;</code>
     * @return int|string
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     * Progress percentage (0-100)
     *
     * Generated from protobuf field <code>int64 progress = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProgress(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->progress = $var;

        return $this;
    }

    /**
     * Error message if failed
     *
     * Generated from protobuf field <code>string reason = 5;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Error message if failed
     *
     * Generated from protobuf field <code>string reason = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setReason(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->reason = $var;

        return $this;
    }

    /**
     * External source used for this job
     *
     * Generated from protobuf field <code>string external_source = 6;</code>
     * @return string
     */
    public function getExternalSource()
    {
        return $this->external_source;
    }

    /**
     * External source used for this job
     *
     * Generated from protobuf field <code>string external_source = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setExternalSource(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->external_source = $var;

        return $this;
    }

    /**
     * Job start timestamp (Unix epoch ms)
     *
     * Generated from protobuf field <code>int64 start_time = 7;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * Job start timestamp (Unix epoch ms)
     *
     * Generated from protobuf field <code>int64 start_time = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Job end timestamp (0 if not completed)
     *
     * Generated from protobuf field <code>int64 end_time = 8;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * Job end timestamp (0 if not completed)
     *
     * Generated from protobuf field <code>int64 end_time = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->end_time = $var;

        return $this;
    }

    /**
     * External spec used for this job
     *
     * Generated from protobuf field <code>string external_spec = 9;</code>
     * @return string
     */
    public function getExternalSpec()
    {
        return $this->external_spec;
    }

    /**
     * External spec used for this job
     *
     * Generated from protobuf field <code>string external_spec = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setExternalSpec(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->external_spec = $var;

        return $this;
    }

}

