<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use UnexpectedValueException;

/**
 * External Collection Refresh APIs
 *
 * Protobuf type <code>milvus.proto.milvus.RefreshExternalCollectionState</code>
 */
class RefreshExternalCollectionState
{
    /**
     * Job is queued, waiting to execute
     *
     * Generated from protobuf enum <code>RefreshPending = 0;</code>
     */
    const RefreshPending = 0;
    /**
     * Job is currently executing
     *
     * Generated from protobuf enum <code>RefreshInProgress = 1;</code>
     */
    const RefreshInProgress = 1;
    /**
     * Job completed successfully
     *
     * Generated from protobuf enum <code>RefreshCompleted = 2;</code>
     */
    const RefreshCompleted = 2;
    /**
     * Job failed with error
     *
     * Generated from protobuf enum <code>RefreshFailed = 3;</code>
     */
    const RefreshFailed = 3;

    private static $valueToName = [
        self::RefreshPending => 'RefreshPending',
        self::RefreshInProgress => 'RefreshInProgress',
        self::RefreshCompleted => 'RefreshCompleted',
        self::RefreshFailed => 'RefreshFailed',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

