<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.RenameCollectionRequest</code>
 */
class RenameCollectionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>string oldName = 3;</code>
     */
    protected $oldName = '';
    /**
     * Generated from protobuf field <code>string newName = 4;</code>
     */
    protected $newName = '';
    /**
     * Generated from protobuf field <code>string newDBName = 5;</code>
     */
    protected $newDBName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $db_name
     *     @type string $oldName
     *     @type string $newName
     *     @type string $newDBName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string oldName = 3;</code>
     * @return string
     */
    public function getOldName()
    {
        return $this->oldName;
    }

    /**
     * Generated from protobuf field <code>string oldName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOldName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->oldName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string newName = 4;</code>
     * @return string
     */
    public function getNewName()
    {
        return $this->newName;
    }

    /**
     * Generated from protobuf field <code>string newName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNewName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->newName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string newDBName = 5;</code>
     * @return string
     */
    public function getNewDBName()
    {
        return $this->newDBName;
    }

    /**
     * Generated from protobuf field <code>string newDBName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNewDBName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->newDBName = $var;

        return $this;
    }

}

