<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ReplicateRequest</code>
 */
class ReplicateRequest extends \Google\Protobuf\Internal\Message
{
    protected $request;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Milvus\ReplicateMessage $replicate_message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.ReplicateMessage replicate_message = 1;</code>
     * @return \Milvus\Proto\Milvus\ReplicateMessage|null
     */
    public function getReplicateMessage()
    {
        return $this->readOneof(1);
    }

    public function hasReplicateMessage()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.milvus.ReplicateMessage replicate_message = 1;</code>
     * @param \Milvus\Proto\Milvus\ReplicateMessage $var
     * @return $this
     */
    public function setReplicateMessage(\Milvus\Proto\Milvus\ReplicateMessage|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        return $this->whichOneof("request");
    }

}

