<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ReplicateMessageRequest</code>
 */
class ReplicateMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string channel_name = 2;</code>
     */
    protected $channel_name = '';
    /**
     * Generated from protobuf field <code>uint64 BeginTs = 3;</code>
     */
    protected $BeginTs = 0;
    /**
     * Generated from protobuf field <code>uint64 EndTs = 4;</code>
     */
    protected $EndTs = 0;
    /**
     * Generated from protobuf field <code>repeated bytes Msgs = 5;</code>
     */
    private $Msgs;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition StartPositions = 6;</code>
     */
    private $StartPositions;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition EndPositions = 7;</code>
     */
    private $EndPositions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $channel_name
     *     @type int|string $BeginTs
     *     @type int|string $EndTs
     *     @type string[] $Msgs
     *     @type \Milvus\Proto\Msg\MsgPosition[] $StartPositions
     *     @type \Milvus\Proto\Msg\MsgPosition[] $EndPositions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel_name = 2;</code>
     * @return string
     */
    public function getChannelName()
    {
        return $this->channel_name;
    }

    /**
     * Generated from protobuf field <code>string channel_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChannelName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->channel_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 BeginTs = 3;</code>
     * @return int|string
     */
    public function getBeginTs()
    {
        return $this->BeginTs;
    }

    /**
     * Generated from protobuf field <code>uint64 BeginTs = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBeginTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->BeginTs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 EndTs = 4;</code>
     * @return int|string
     */
    public function getEndTs()
    {
        return $this->EndTs;
    }

    /**
     * Generated from protobuf field <code>uint64 EndTs = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->EndTs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Msgs = 5;</code>
     * @return RepeatedField<string>
     */
    public function getMsgs()
    {
        return $this->Msgs;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Msgs = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setMsgs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Msgs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition StartPositions = 6;</code>
     * @return RepeatedField<\Milvus\Proto\Msg\MsgPosition>
     */
    public function getStartPositions()
    {
        return $this->StartPositions;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition StartPositions = 6;</code>
     * @param \Milvus\Proto\Msg\MsgPosition[] $var
     * @return $this
     */
    public function setStartPositions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Msg\MsgPosition::class);
        $this->StartPositions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition EndPositions = 7;</code>
     * @return RepeatedField<\Milvus\Proto\Msg\MsgPosition>
     */
    public function getEndPositions()
    {
        return $this->EndPositions;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.msg.MsgPosition EndPositions = 7;</code>
     * @param \Milvus\Proto\Msg\MsgPosition[] $var
     * @return $this
     */
    public function setEndPositions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Msg\MsgPosition::class);
        $this->EndPositions = $arr;

        return $this;
    }

}

