<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ReplicateConfirmedMessageInfo</code>
 */
class ReplicateConfirmedMessageInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * the source time tick of the last confirmed message that persisted into target WAL. 
     *
     * Generated from protobuf field <code>uint64 confirmed_time_tick = 1;</code>
     */
    protected $confirmed_time_tick = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $confirmed_time_tick
     *           the source time tick of the last confirmed message that persisted into target WAL. 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * the source time tick of the last confirmed message that persisted into target WAL. 
     *
     * Generated from protobuf field <code>uint64 confirmed_time_tick = 1;</code>
     * @return int|string
     */
    public function getConfirmedTimeTick()
    {
        return $this->confirmed_time_tick;
    }

    /**
     * the source time tick of the last confirmed message that persisted into target WAL. 
     *
     * Generated from protobuf field <code>uint64 confirmed_time_tick = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConfirmedTimeTick(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->confirmed_time_tick = $var;

        return $this;
    }

}

