<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ResourceGroup</code>
 */
class ResourceGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 capacity = 2;</code>
     */
    protected $capacity = 0;
    /**
     * Generated from protobuf field <code>int32 num_available_node = 3;</code>
     */
    protected $num_available_node = 0;
    /**
     * collection name -> loaded replica num
     *
     * Generated from protobuf field <code>map<string, int32> num_loaded_replica = 4;</code>
     */
    private $num_loaded_replica;
    /**
     * collection name -> accessed other rg's node num
     *
     * Generated from protobuf field <code>map<string, int32> num_outgoing_node = 5;</code>
     */
    private $num_outgoing_node;
    /**
     * collection name -> be accessed node num by other rg
     *
     * Generated from protobuf field <code>map<string, int32> num_incoming_node = 6;</code>
     */
    private $num_incoming_node;
    /**
     * resource group configuration.
     *
     * Generated from protobuf field <code>.milvus.proto.rg.ResourceGroupConfig config = 7;</code>
     */
    protected $config = null;
    /**
     * query node belong to this resource group now.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.NodeInfo nodes = 8;</code>
     */
    private $nodes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $capacity
     *     @type int $num_available_node
     *     @type array|\Google\Protobuf\Internal\MapField $num_loaded_replica
     *           collection name -> loaded replica num
     *     @type array|\Google\Protobuf\Internal\MapField $num_outgoing_node
     *           collection name -> accessed other rg's node num
     *     @type array|\Google\Protobuf\Internal\MapField $num_incoming_node
     *           collection name -> be accessed node num by other rg
     *     @type \Milvus\Proto\Rg\ResourceGroupConfig $config
     *           resource group configuration.
     *     @type \Milvus\Proto\Common\NodeInfo[] $nodes
     *           query node belong to this resource group now.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 capacity = 2;</code>
     * @return int
     */
    public function getCapacity()
    {
        return $this->capacity;
    }

    /**
     * Generated from protobuf field <code>int32 capacity = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCapacity(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->capacity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 num_available_node = 3;</code>
     * @return int
     */
    public function getNumAvailableNode()
    {
        return $this->num_available_node;
    }

    /**
     * Generated from protobuf field <code>int32 num_available_node = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNumAvailableNode(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->num_available_node = $var;

        return $this;
    }

    /**
     * collection name -> loaded replica num
     *
     * Generated from protobuf field <code>map<string, int32> num_loaded_replica = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getNumLoadedReplica()
    {
        return $this->num_loaded_replica;
    }

    /**
     * collection name -> loaded replica num
     *
     * Generated from protobuf field <code>map<string, int32> num_loaded_replica = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setNumLoadedReplica(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->num_loaded_replica = $arr;

        return $this;
    }

    /**
     * collection name -> accessed other rg's node num
     *
     * Generated from protobuf field <code>map<string, int32> num_outgoing_node = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getNumOutgoingNode()
    {
        return $this->num_outgoing_node;
    }

    /**
     * collection name -> accessed other rg's node num
     *
     * Generated from protobuf field <code>map<string, int32> num_outgoing_node = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setNumOutgoingNode(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->num_outgoing_node = $arr;

        return $this;
    }

    /**
     * collection name -> be accessed node num by other rg
     *
     * Generated from protobuf field <code>map<string, int32> num_incoming_node = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getNumIncomingNode()
    {
        return $this->num_incoming_node;
    }

    /**
     * collection name -> be accessed node num by other rg
     *
     * Generated from protobuf field <code>map<string, int32> num_incoming_node = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setNumIncomingNode(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->num_incoming_node = $arr;

        return $this;
    }

    /**
     * resource group configuration.
     *
     * Generated from protobuf field <code>.milvus.proto.rg.ResourceGroupConfig config = 7;</code>
     * @return \Milvus\Proto\Rg\ResourceGroupConfig|null
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function hasConfig()
    {
        return isset($this->config);
    }

    public function clearConfig()
    {
        unset($this->config);
    }

    /**
     * resource group configuration.
     *
     * Generated from protobuf field <code>.milvus.proto.rg.ResourceGroupConfig config = 7;</code>
     * @param \Milvus\Proto\Rg\ResourceGroupConfig $var
     * @return $this
     */
    public function setConfig(\Milvus\Proto\Rg\ResourceGroupConfig|null $var)
    {
        $this->config = $var;

        return $this;
    }

    /**
     * query node belong to this resource group now.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.NodeInfo nodes = 8;</code>
     * @return RepeatedField<\Milvus\Proto\Common\NodeInfo>
     */
    public function getNodes()
    {
        return $this->nodes;
    }

    /**
     * query node belong to this resource group now.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.NodeInfo nodes = 8;</code>
     * @param \Milvus\Proto\Common\NodeInfo[] $var
     * @return $this
     */
    public function setNodes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\NodeInfo::class);
        $this->nodes = $arr;

        return $this;
    }

}

