<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use UnexpectedValueException;

/**
 * Protobuf type <code>milvus.proto.milvus.RestoreSnapshotState</code>
 */
class RestoreSnapshotState
{
    /**
     * Generated from protobuf enum <code>RestoreSnapshotNone = 0;</code>
     */
    const RestoreSnapshotNone = 0;
    /**
     * Job created, waiting to start
     *
     * Generated from protobuf enum <code>RestoreSnapshotPending = 1;</code>
     */
    const RestoreSnapshotPending = 1;
    /**
     * Executing restore snapshot job
     *
     * Generated from protobuf enum <code>RestoreSnapshotExecuting = 2;</code>
     */
    const RestoreSnapshotExecuting = 2;
    /**
     * All done
     *
     * Generated from protobuf enum <code>RestoreSnapshotCompleted = 3;</code>
     */
    const RestoreSnapshotCompleted = 3;
    /**
     * Failed
     *
     * Generated from protobuf enum <code>RestoreSnapshotFailed = 4;</code>
     */
    const RestoreSnapshotFailed = 4;

    private static $valueToName = [
        self::RestoreSnapshotNone => 'RestoreSnapshotNone',
        self::RestoreSnapshotPending => 'RestoreSnapshotPending',
        self::RestoreSnapshotExecuting => 'RestoreSnapshotExecuting',
        self::RestoreSnapshotCompleted => 'RestoreSnapshotCompleted',
        self::RestoreSnapshotFailed => 'RestoreSnapshotFailed',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

