<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use UnexpectedValueException;

/**
 * Row Policy Action enum
 *
 * Protobuf type <code>milvus.proto.milvus.RowPolicyAction</code>
 */
class RowPolicyAction
{
    /**
     * Generated from protobuf enum <code>Query = 0;</code>
     */
    const Query = 0;
    /**
     * Generated from protobuf enum <code>Search = 1;</code>
     */
    const Search = 1;
    /**
     * Generated from protobuf enum <code>Insert = 2;</code>
     */
    const Insert = 2;
    /**
     * Generated from protobuf enum <code>Delete = 3;</code>
     */
    const Delete = 3;
    /**
     * Generated from protobuf enum <code>Upsert = 4;</code>
     */
    const Upsert = 4;

    private static $valueToName = [
        self::Query => 'Query',
        self::Search => 'Search',
        self::Insert => 'Insert',
        self::Delete => 'Delete',
        self::Upsert => 'Upsert',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

