<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.SearchRequest</code>
 */
class SearchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * must
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     */
    protected $collection_name = '';
    /**
     * must
     *
     * Generated from protobuf field <code>repeated string partition_names = 4;</code>
     */
    private $partition_names;
    /**
     * must
     *
     * Generated from protobuf field <code>string dsl = 5;</code>
     */
    protected $dsl = '';
    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.DslType dsl_type = 7;</code>
     */
    protected $dsl_type = 0;
    /**
     * Generated from protobuf field <code>repeated string output_fields = 8;</code>
     */
    private $output_fields;
    /**
     * must
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair search_params = 9;</code>
     */
    private $search_params;
    /**
     * Generated from protobuf field <code>uint64 travel_timestamp = 10;</code>
     */
    protected $travel_timestamp = 0;
    /**
     * guarantee_timestamp
     *
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 11;</code>
     */
    protected $guarantee_timestamp = 0;
    /**
     * Generated from protobuf field <code>int64 nq = 12;</code>
     */
    protected $nq = 0;
    /**
     * Generated from protobuf field <code>bool not_return_all_meta = 13;</code>
     */
    protected $not_return_all_meta = false;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 14;</code>
     */
    protected $consistency_level = 0;
    /**
     * Generated from protobuf field <code>bool use_default_consistency = 15;</code>
     */
    protected $use_default_consistency = false;
    /**
     * use search_input instead
     *
     * Generated from protobuf field <code>bool search_by_primary_keys = 16 [deprecated = true];</code>
     * @deprecated
     */
    protected $search_by_primary_keys = false;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.SubSearchRequest sub_reqs = 17;</code>
     */
    private $sub_reqs;
    /**
     * Generated from protobuf field <code>map<string, .milvus.proto.schema.TemplateValue> expr_template_values = 18;</code>
     */
    private $expr_template_values;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FunctionScore function_score = 19;</code>
     */
    protected $function_score = null;
    /**
     * Generated from protobuf field <code>optional string namespace = 20;</code>
     */
    protected $namespace = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Highlighter highlighter = 21;</code>
     */
    protected $highlighter = null;
    protected $search_input;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *           must
     *     @type string $db_name
     *     @type string $collection_name
     *           must
     *     @type string[] $partition_names
     *           must
     *     @type string $dsl
     *           must
     *     @type string $placeholder_group
     *           serialized `PlaceholderGroup` for vector search
     *     @type \Milvus\Proto\Schema\IDs $ids
     *           primary keys for search by IDs
     *     @type int $dsl_type
     *           must
     *     @type string[] $output_fields
     *     @type \Milvus\Proto\Common\KeyValuePair[] $search_params
     *           must
     *     @type int|string $travel_timestamp
     *     @type int|string $guarantee_timestamp
     *           guarantee_timestamp
     *     @type int|string $nq
     *     @type bool $not_return_all_meta
     *     @type int $consistency_level
     *     @type bool $use_default_consistency
     *     @type bool $search_by_primary_keys
     *           use search_input instead
     *     @type \Milvus\Proto\Milvus\SubSearchRequest[] $sub_reqs
     *     @type array|\Google\Protobuf\Internal\MapField $expr_template_values
     *     @type \Milvus\Proto\Schema\FunctionScore $function_score
     *     @type string $namespace
     *     @type \Milvus\Proto\Common\Highlighter $highlighter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated string partition_names = 4;</code>
     * @return RepeatedField<string>
     */
    public function getPartitionNames()
    {
        return $this->partition_names;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated string partition_names = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPartitionNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->partition_names = $arr;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>string dsl = 5;</code>
     * @return string
     */
    public function getDsl()
    {
        return $this->dsl;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>string dsl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDsl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->dsl = $var;

        return $this;
    }

    /**
     * serialized `PlaceholderGroup` for vector search
     *
     * Generated from protobuf field <code>bytes placeholder_group = 6;</code>
     * @return string
     */
    public function getPlaceholderGroup()
    {
        return $this->readOneof(6);
    }

    public function hasPlaceholderGroup()
    {
        return $this->hasOneof(6);
    }

    /**
     * serialized `PlaceholderGroup` for vector search
     *
     * Generated from protobuf field <code>bytes placeholder_group = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceholderGroup(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * primary keys for search by IDs
     *
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 22;</code>
     * @return \Milvus\Proto\Schema\IDs|null
     */
    public function getIds()
    {
        return $this->readOneof(22);
    }

    public function hasIds()
    {
        return $this->hasOneof(22);
    }

    /**
     * primary keys for search by IDs
     *
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 22;</code>
     * @param \Milvus\Proto\Schema\IDs $var
     * @return $this
     */
    public function setIds(\Milvus\Proto\Schema\IDs|null $var)
    {
        $this->writeOneof(22, $var);

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.DslType dsl_type = 7;</code>
     * @return int one of the values in {@see \Milvus\Proto\Common\DslType}
     */
    public function getDslType()
    {
        return $this->dsl_type;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>.milvus.proto.common.DslType dsl_type = 7;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Common\DslType}
     * @return $this
     */
    public function setDslType(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\DslType::class);
        $this->dsl_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string output_fields = 8;</code>
     * @return RepeatedField<string>
     */
    public function getOutputFields()
    {
        return $this->output_fields;
    }

    /**
     * Generated from protobuf field <code>repeated string output_fields = 8;</code>
     * @param string[] $var
     * @return $this
     */
    public function setOutputFields(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->output_fields = $arr;

        return $this;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair search_params = 9;</code>
     * @return RepeatedField<\Milvus\Proto\Common\KeyValuePair>
     */
    public function getSearchParams()
    {
        return $this->search_params;
    }

    /**
     * must
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair search_params = 9;</code>
     * @param \Milvus\Proto\Common\KeyValuePair[] $var
     * @return $this
     */
    public function setSearchParams(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->search_params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 travel_timestamp = 10;</code>
     * @return int|string
     */
    public function getTravelTimestamp()
    {
        return $this->travel_timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 travel_timestamp = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTravelTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->travel_timestamp = $var;

        return $this;
    }

    /**
     * guarantee_timestamp
     *
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 11;</code>
     * @return int|string
     */
    public function getGuaranteeTimestamp()
    {
        return $this->guarantee_timestamp;
    }

    /**
     * guarantee_timestamp
     *
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGuaranteeTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->guarantee_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 nq = 12;</code>
     * @return int|string
     */
    public function getNq()
    {
        return $this->nq;
    }

    /**
     * Generated from protobuf field <code>int64 nq = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNq(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->nq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool not_return_all_meta = 13;</code>
     * @return bool
     */
    public function getNotReturnAllMeta()
    {
        return $this->not_return_all_meta;
    }

    /**
     * Generated from protobuf field <code>bool not_return_all_meta = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setNotReturnAllMeta(bool $var)
    {
        $this->not_return_all_meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 14;</code>
     * @return int one of the values in {@see \Milvus\Proto\Common\ConsistencyLevel}
     */
    public function getConsistencyLevel()
    {
        return $this->consistency_level;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConsistencyLevel consistency_level = 14;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Common\ConsistencyLevel}
     * @return $this
     */
    public function setConsistencyLevel(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\ConsistencyLevel::class);
        $this->consistency_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_default_consistency = 15;</code>
     * @return bool
     */
    public function getUseDefaultConsistency()
    {
        return $this->use_default_consistency;
    }

    /**
     * Generated from protobuf field <code>bool use_default_consistency = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseDefaultConsistency(bool $var)
    {
        $this->use_default_consistency = $var;

        return $this;
    }

    /**
     * use search_input instead
     *
     * Generated from protobuf field <code>bool search_by_primary_keys = 16 [deprecated = true];</code>
     * @return bool
     * @deprecated
     */
    public function getSearchByPrimaryKeys()
    {
        if ($this->search_by_primary_keys !== false) {
            @trigger_error('search_by_primary_keys is deprecated.', E_USER_DEPRECATED);
        }
        return $this->search_by_primary_keys;
    }

    /**
     * use search_input instead
     *
     * Generated from protobuf field <code>bool search_by_primary_keys = 16 [deprecated = true];</code>
     * @param bool $var
     * @return $this
     * @deprecated
     */
    public function setSearchByPrimaryKeys(bool $var)
    {
        @trigger_error('search_by_primary_keys is deprecated.', E_USER_DEPRECATED);
        $this->search_by_primary_keys = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.SubSearchRequest sub_reqs = 17;</code>
     * @return RepeatedField<\Milvus\Proto\Milvus\SubSearchRequest>
     */
    public function getSubReqs()
    {
        return $this->sub_reqs;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.SubSearchRequest sub_reqs = 17;</code>
     * @param \Milvus\Proto\Milvus\SubSearchRequest[] $var
     * @return $this
     */
    public function setSubReqs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\SubSearchRequest::class);
        $this->sub_reqs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .milvus.proto.schema.TemplateValue> expr_template_values = 18;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getExprTemplateValues()
    {
        return $this->expr_template_values;
    }

    /**
     * Generated from protobuf field <code>map<string, .milvus.proto.schema.TemplateValue> expr_template_values = 18;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setExprTemplateValues(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\TemplateValue::class);
        $this->expr_template_values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FunctionScore function_score = 19;</code>
     * @return \Milvus\Proto\Schema\FunctionScore|null
     */
    public function getFunctionScore()
    {
        return $this->function_score;
    }

    public function hasFunctionScore()
    {
        return isset($this->function_score);
    }

    public function clearFunctionScore()
    {
        unset($this->function_score);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.FunctionScore function_score = 19;</code>
     * @param \Milvus\Proto\Schema\FunctionScore $var
     * @return $this
     */
    public function setFunctionScore(\Milvus\Proto\Schema\FunctionScore|null $var)
    {
        $this->function_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string namespace = 20;</code>
     * @return string
     */
    public function getNamespace()
    {
        return isset($this->namespace) ? $this->namespace : '';
    }

    public function hasNamespace()
    {
        return isset($this->namespace);
    }

    public function clearNamespace()
    {
        unset($this->namespace);
    }

    /**
     * Generated from protobuf field <code>optional string namespace = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Highlighter highlighter = 21;</code>
     * @return \Milvus\Proto\Common\Highlighter|null
     */
    public function getHighlighter()
    {
        return $this->highlighter;
    }

    public function hasHighlighter()
    {
        return isset($this->highlighter);
    }

    public function clearHighlighter()
    {
        unset($this->highlighter);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Highlighter highlighter = 21;</code>
     * @param \Milvus\Proto\Common\Highlighter $var
     * @return $this
     */
    public function setHighlighter(\Milvus\Proto\Common\Highlighter|null $var)
    {
        $this->highlighter = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getSearchInput()
    {
        return $this->whichOneof("search_input");
    }

}

