<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * List all partitions for particular collection response.
 * The returned datas are all rows, we can format to columns by therir index.
 *
 * Generated from protobuf message <code>milvus.proto.milvus.ShowPartitionsResponse</code>
 */
class ShowPartitionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Contain error_code and reason
     *
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * All partition names for this collection
     *
     * Generated from protobuf field <code>repeated string partition_names = 2;</code>
     */
    private $partition_names;
    /**
     * All partition ids for this collection
     *
     * Generated from protobuf field <code>repeated int64 partitionIDs = 3;</code>
     */
    private $partitionIDs;
    /**
     * All hybrid timestamps
     *
     * Generated from protobuf field <code>repeated uint64 created_timestamps = 4;</code>
     */
    private $created_timestamps;
    /**
     * All utc timestamps calculated by created_timestamps
     *
     * Generated from protobuf field <code>repeated uint64 created_utc_timestamps = 5;</code>
     */
    private $created_utc_timestamps;
    /**
     * Load percentage on querynode
     * Deprecated: use GetLoadingProgress rpc instead
     *
     * Generated from protobuf field <code>repeated int64 inMemory_percentages = 6 [deprecated = true];</code>
     * @deprecated
     */
    private $inMemory_percentages;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *           Contain error_code and reason
     *     @type string[] $partition_names
     *           All partition names for this collection
     *     @type int[]|string[] $partitionIDs
     *           All partition ids for this collection
     *     @type int[]|string[] $created_timestamps
     *           All hybrid timestamps
     *     @type int[]|string[] $created_utc_timestamps
     *           All utc timestamps calculated by created_timestamps
     *     @type int[]|string[] $inMemory_percentages
     *           Load percentage on querynode
     *           Deprecated: use GetLoadingProgress rpc instead
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Contain error_code and reason
     *
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Contain error_code and reason
     *
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus(\Milvus\Proto\Common\Status|null $var)
    {
        $this->status = $var;

        return $this;
    }

    /**
     * All partition names for this collection
     *
     * Generated from protobuf field <code>repeated string partition_names = 2;</code>
     * @return RepeatedField<string>
     */
    public function getPartitionNames()
    {
        return $this->partition_names;
    }

    /**
     * All partition names for this collection
     *
     * Generated from protobuf field <code>repeated string partition_names = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPartitionNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->partition_names = $arr;

        return $this;
    }

    /**
     * All partition ids for this collection
     *
     * Generated from protobuf field <code>repeated int64 partitionIDs = 3;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getPartitionIDs()
    {
        return $this->partitionIDs;
    }

    /**
     * All partition ids for this collection
     *
     * Generated from protobuf field <code>repeated int64 partitionIDs = 3;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setPartitionIDs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->partitionIDs = $arr;

        return $this;
    }

    /**
     * All hybrid timestamps
     *
     * Generated from protobuf field <code>repeated uint64 created_timestamps = 4;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getCreatedTimestamps()
    {
        return $this->created_timestamps;
    }

    /**
     * All hybrid timestamps
     *
     * Generated from protobuf field <code>repeated uint64 created_timestamps = 4;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setCreatedTimestamps(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->created_timestamps = $arr;

        return $this;
    }

    /**
     * All utc timestamps calculated by created_timestamps
     *
     * Generated from protobuf field <code>repeated uint64 created_utc_timestamps = 5;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getCreatedUtcTimestamps()
    {
        return $this->created_utc_timestamps;
    }

    /**
     * All utc timestamps calculated by created_timestamps
     *
     * Generated from protobuf field <code>repeated uint64 created_utc_timestamps = 5;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setCreatedUtcTimestamps(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->created_utc_timestamps = $arr;

        return $this;
    }

    /**
     * Load percentage on querynode
     * Deprecated: use GetLoadingProgress rpc instead
     *
     * Generated from protobuf field <code>repeated int64 inMemory_percentages = 6 [deprecated = true];</code>
     * @return RepeatedField<int>|RepeatedField<string>
     * @deprecated
     */
    public function getInMemoryPercentages()
    {
        if (count($this->inMemory_percentages) !== 0) {
            @trigger_error('inMemory_percentages is deprecated.', E_USER_DEPRECATED);
        }
        return $this->inMemory_percentages;
    }

    /**
     * Load percentage on querynode
     * Deprecated: use GetLoadingProgress rpc instead
     *
     * Generated from protobuf field <code>repeated int64 inMemory_percentages = 6 [deprecated = true];</code>
     * @param int[]|string[] $var
     * @return $this
     * @deprecated
     */
    public function setInMemoryPercentages(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        if (count($arr) !== 0) {
            @trigger_error('inMemory_percentages is deprecated.', E_USER_DEPRECATED);
        }
        $this->inMemory_percentages = $arr;

        return $this;
    }

}

