<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.UpsertRequest</code>
 */
class UpsertRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     */
    protected $collection_name = '';
    /**
     * Generated from protobuf field <code>string partition_name = 4;</code>
     */
    protected $partition_name = '';
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 5;</code>
     */
    private $fields_data;
    /**
     * Generated from protobuf field <code>repeated uint32 hash_keys = 6;</code>
     */
    private $hash_keys;
    /**
     * Generated from protobuf field <code>uint32 num_rows = 7;</code>
     */
    protected $num_rows = 0;
    /**
     * Generated from protobuf field <code>uint64 schema_timestamp = 8;</code>
     */
    protected $schema_timestamp = 0;
    /**
     * Generated from protobuf field <code>bool partial_update = 9;</code>
     */
    protected $partial_update = false;
    /**
     * Generated from protobuf field <code>optional string namespace = 10;</code>
     */
    protected $namespace = null;
    /**
     * field_ops carries per-field FieldPartialUpdateOp directives describing
     * how each FieldData should be merged during a partial upsert. Ops are
     * matched to fields_data entries by field_name. A non-REPLACE op implies
     * partial_update=true regardless of the partial_update flag.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldPartialUpdateOp field_ops = 11;</code>
     */
    private $field_ops;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $db_name
     *     @type string $collection_name
     *     @type string $partition_name
     *     @type \Milvus\Proto\Schema\FieldData[] $fields_data
     *     @type int[] $hash_keys
     *     @type int $num_rows
     *     @type int|string $schema_timestamp
     *     @type bool $partial_update
     *     @type string $namespace
     *     @type \Milvus\Proto\Schema\FieldPartialUpdateOp[] $field_ops
     *           field_ops carries per-field FieldPartialUpdateOp directives describing
     *           how each FieldData should be merged during a partial upsert. Ops are
     *           matched to fields_data entries by field_name. A non-REPLACE op implies
     *           partial_update=true regardless of the partial_update flag.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase(\Milvus\Proto\Common\MsgBase|null $var)
    {
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string partition_name = 4;</code>
     * @return string
     */
    public function getPartitionName()
    {
        return $this->partition_name;
    }

    /**
     * Generated from protobuf field <code>string partition_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPartitionName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->partition_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 5;</code>
     * @return RepeatedField<\Milvus\Proto\Schema\FieldData>
     */
    public function getFieldsData()
    {
        return $this->fields_data;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 5;</code>
     * @param \Milvus\Proto\Schema\FieldData[] $var
     * @return $this
     */
    public function setFieldsData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldData::class);
        $this->fields_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 hash_keys = 6;</code>
     * @return RepeatedField<int>
     */
    public function getHashKeys()
    {
        return $this->hash_keys;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 hash_keys = 6;</code>
     * @param int[] $var
     * @return $this
     */
    public function setHashKeys(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->hash_keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_rows = 7;</code>
     * @return int
     */
    public function getNumRows()
    {
        return $this->num_rows;
    }

    /**
     * Generated from protobuf field <code>uint32 num_rows = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setNumRows(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->num_rows = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 schema_timestamp = 8;</code>
     * @return int|string
     */
    public function getSchemaTimestamp()
    {
        return $this->schema_timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 schema_timestamp = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchemaTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->schema_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool partial_update = 9;</code>
     * @return bool
     */
    public function getPartialUpdate()
    {
        return $this->partial_update;
    }

    /**
     * Generated from protobuf field <code>bool partial_update = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setPartialUpdate(bool $var)
    {
        $this->partial_update = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string namespace = 10;</code>
     * @return string
     */
    public function getNamespace()
    {
        return isset($this->namespace) ? $this->namespace : '';
    }

    public function hasNamespace()
    {
        return isset($this->namespace);
    }

    public function clearNamespace()
    {
        unset($this->namespace);
    }

    /**
     * Generated from protobuf field <code>optional string namespace = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->namespace = $var;

        return $this;
    }

    /**
     * field_ops carries per-field FieldPartialUpdateOp directives describing
     * how each FieldData should be merged during a partial upsert. Ops are
     * matched to fields_data entries by field_name. A non-REPLACE op implies
     * partial_update=true regardless of the partial_update flag.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldPartialUpdateOp field_ops = 11;</code>
     * @return RepeatedField<\Milvus\Proto\Schema\FieldPartialUpdateOp>
     */
    public function getFieldOps()
    {
        return $this->field_ops;
    }

    /**
     * field_ops carries per-field FieldPartialUpdateOp directives describing
     * how each FieldData should be merged during a partial upsert. Ops are
     * matched to fields_data entries by field_name. A non-REPLACE op implies
     * partial_update=true regardless of the partial_update flag.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldPartialUpdateOp field_ops = 11;</code>
     * @param \Milvus\Proto\Schema\FieldPartialUpdateOp[] $var
     * @return $this
     */
    public function setFieldOps(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldPartialUpdateOp::class);
        $this->field_ops = $arr;

        return $this;
    }

}

