<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.common.ClientCommand</code>
 */
class ClientCommand extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string command_id = 1;</code>
     */
    protected $command_id = '';
    /**
     * Generated from protobuf field <code>string command_type = 2;</code>
     */
    protected $command_type = '';
    /**
     * Generated from protobuf field <code>bytes payload = 3;</code>
     */
    protected $payload = '';
    /**
     * Generated from protobuf field <code>int64 create_time = 4;</code>
     */
    protected $create_time = 0;
    /**
     * Generated from protobuf field <code>bool persistent = 5;</code>
     */
    protected $persistent = false;
    /**
     * Generated from protobuf field <code>string target_scope = 6;</code>
     */
    protected $target_scope = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $command_id
     *     @type string $command_type
     *     @type string $payload
     *     @type int|string $create_time
     *     @type bool $persistent
     *     @type string $target_scope
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string command_id = 1;</code>
     * @return string
     */
    public function getCommandId()
    {
        return $this->command_id;
    }

    /**
     * Generated from protobuf field <code>string command_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCommandId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->command_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string command_type = 2;</code>
     * @return string
     */
    public function getCommandType()
    {
        return $this->command_type;
    }

    /**
     * Generated from protobuf field <code>string command_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCommandType(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->command_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 3;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->payload = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 create_time = 4;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>int64 create_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool persistent = 5;</code>
     * @return bool
     */
    public function getPersistent()
    {
        return $this->persistent;
    }

    /**
     * Generated from protobuf field <code>bool persistent = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setPersistent(bool $var)
    {
        $this->persistent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_scope = 6;</code>
     * @return string
     */
    public function getTargetScope()
    {
        return $this->target_scope;
    }

    /**
     * Generated from protobuf field <code>string target_scope = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetScope(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->target_scope = $var;

        return $this;
    }

}

