<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.common.CommandReply</code>
 */
class CommandReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string command_id = 1;</code>
     */
    protected $command_id = '';
    /**
     * Generated from protobuf field <code>bool success = 2;</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     */
    protected $error_message = '';
    /**
     * Generated from protobuf field <code>bytes payload = 4;</code>
     */
    protected $payload = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $command_id
     *     @type bool $success
     *     @type string $error_message
     *     @type string $payload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string command_id = 1;</code>
     * @return string
     */
    public function getCommandId()
    {
        return $this->command_id;
    }

    /**
     * Generated from protobuf field <code>string command_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCommandId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->command_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool success = 2;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess(bool $var)
    {
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->error_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 4;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->payload = $var;

        return $this;
    }

}

