<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * CrossClusterTopology is the topology that 
 * describes the topology cross multiple cluster milvus.
 *
 * Generated from protobuf message <code>milvus.proto.common.CrossClusterTopology</code>
 */
class CrossClusterTopology extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string source_cluster_id = 1;</code>
     */
    protected $source_cluster_id = '';
    /**
     * Generated from protobuf field <code>string target_cluster_id = 2;</code>
     */
    protected $target_cluster_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source_cluster_id
     *     @type string $target_cluster_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string source_cluster_id = 1;</code>
     * @return string
     */
    public function getSourceClusterId()
    {
        return $this->source_cluster_id;
    }

    /**
     * Generated from protobuf field <code>string source_cluster_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceClusterId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->source_cluster_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_cluster_id = 2;</code>
     * @return string
     */
    public function getTargetClusterId()
    {
        return $this->target_cluster_id;
    }

    /**
     * Generated from protobuf field <code>string target_cluster_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetClusterId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->target_cluster_id = $var;

        return $this;
    }

}

