<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.common.HighlightResult</code>
 */
class HighlightResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     */
    protected $field_name = '';
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.HighlightData datas = 2;</code>
     */
    private $datas;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field_name
     *     @type \Milvus\Proto\Common\HighlightData[] $datas
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Generated from protobuf field <code>string field_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->field_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.HighlightData datas = 2;</code>
     * @return RepeatedField<\Milvus\Proto\Common\HighlightData>
     */
    public function getDatas()
    {
        return $this->datas;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.HighlightData datas = 2;</code>
     * @param \Milvus\Proto\Common\HighlightData[] $var
     * @return $this
     */
    public function setDatas(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\HighlightData::class);
        $this->datas = $arr;

        return $this;
    }

}

