<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.common.HighlightData</code>
 */
class HighlightData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string fragments = 1;</code>
     */
    private $fragments;
    /**
     * Generated from protobuf field <code>repeated float scores = 2;</code>
     */
    private $scores;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $fragments
     *     @type float[] $scores
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string fragments = 1;</code>
     * @return RepeatedField<string>
     */
    public function getFragments()
    {
        return $this->fragments;
    }

    /**
     * Generated from protobuf field <code>repeated string fragments = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setFragments(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->fragments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float scores = 2;</code>
     * @return RepeatedField<float>
     */
    public function getScores()
    {
        return $this->scores;
    }

    /**
     * Generated from protobuf field <code>repeated float scores = 2;</code>
     * @param float[] $var
     * @return $this
     */
    public function setScores(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->scores = $arr;

        return $this;
    }

}

