<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.common.MessageID</code>
 */
class MessageID extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.milvus.proto.common.WALName WAL_name = 2;</code>
     */
    protected $WAL_name = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type int $WAL_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.WALName WAL_name = 2;</code>
     * @return int one of the values in {@see \Milvus\Proto\Common\WALName}
     */
    public function getWALName()
    {
        return $this->WAL_name;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.WALName WAL_name = 2;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Common\WALName}
     * @return $this
     */
    public function setWALName(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\WALName::class);
        $this->WAL_name = $var;

        return $this;
    }

}

