<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.common.MetricAggSpec</code>
 */
class MetricAggSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * "avg" | "sum" | "count" | "min" | "max"
     *
     * Generated from protobuf field <code>string op = 1;</code>
     */
    protected $op = '';
    /**
     * field name | "_score" | "*" (count(*))
     *
     * Generated from protobuf field <code>string field_name = 2;</code>
     */
    protected $field_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $op
     *           "avg" | "sum" | "count" | "min" | "max"
     *     @type string $field_name
     *           field name | "_score" | "*" (count(*))
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * "avg" | "sum" | "count" | "min" | "max"
     *
     * Generated from protobuf field <code>string op = 1;</code>
     * @return string
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * "avg" | "sum" | "count" | "min" | "max"
     *
     * Generated from protobuf field <code>string op = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOp(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->op = $var;

        return $this;
    }

    /**
     * field name | "_score" | "*" (count(*))
     *
     * Generated from protobuf field <code>string field_name = 2;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * field name | "_score" | "*" (count(*))
     *
     * Generated from protobuf field <code>string field_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->field_name = $var;

        return $this;
    }

}

