<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * MilvusCluster describes the Milvus cluster information, 
 * including pchannel mapping details.
 *
 * Generated from protobuf message <code>milvus.proto.common.MilvusCluster</code>
 */
class MilvusCluster extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string cluster_id = 1;</code>
     */
    protected $cluster_id = '';
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConnectionParam connection_param = 2;</code>
     */
    protected $connection_param = null;
    /**
     * Generated from protobuf field <code>repeated string pchannels = 3;</code>
     */
    private $pchannels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cluster_id
     *     @type \Milvus\Proto\Common\ConnectionParam $connection_param
     *     @type string[] $pchannels
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cluster_id = 1;</code>
     * @return string
     */
    public function getClusterId()
    {
        return $this->cluster_id;
    }

    /**
     * Generated from protobuf field <code>string cluster_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClusterId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->cluster_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConnectionParam connection_param = 2;</code>
     * @return \Milvus\Proto\Common\ConnectionParam|null
     */
    public function getConnectionParam()
    {
        return $this->connection_param;
    }

    public function hasConnectionParam()
    {
        return isset($this->connection_param);
    }

    public function clearConnectionParam()
    {
        unset($this->connection_param);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ConnectionParam connection_param = 2;</code>
     * @param \Milvus\Proto\Common\ConnectionParam $var
     * @return $this
     */
    public function setConnectionParam(\Milvus\Proto\Common\ConnectionParam|null $var)
    {
        $this->connection_param = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string pchannels = 3;</code>
     * @return RepeatedField<string>
     */
    public function getPchannels()
    {
        return $this->pchannels;
    }

    /**
     * Generated from protobuf field <code>repeated string pchannels = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPchannels(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pchannels = $arr;

        return $this;
    }

}

