<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>milvus.proto.common.PlaceholderValue</code>
 */
class PlaceholderValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     */
    protected $tag = '';
    /**
     * Generated from protobuf field <code>.milvus.proto.common.PlaceholderType type = 2;</code>
     */
    protected $type = 0;
    /**
     * values is a 2d-array of nq rows, every row contains a query vector.
     * for dense vector, all rows are of the same length; for sparse vector,
     * the length of each row may vary depending on their number of non-zeros.
     *
     * Generated from protobuf field <code>repeated bytes values = 3;</code>
     */
    private $values;
    /**
     * Generated from protobuf field <code>bool element_level = 4;</code>
     */
    protected $element_level = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *     @type int $type
     *     @type string[] $values
     *           values is a 2d-array of nq rows, every row contains a query vector.
     *           for dense vector, all rows are of the same length; for sparse vector,
     *           the length of each row may vary depending on their number of non-zeros.
     *     @type bool $element_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.PlaceholderType type = 2;</code>
     * @return int one of the values in {@see \Milvus\Proto\Common\PlaceholderType}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.PlaceholderType type = 2;</code>
     * @param int $var one of the values in {@see \Milvus\Proto\Common\PlaceholderType}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\PlaceholderType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * values is a 2d-array of nq rows, every row contains a query vector.
     * for dense vector, all rows are of the same length; for sparse vector,
     * the length of each row may vary depending on their number of non-zeros.
     *
     * Generated from protobuf field <code>repeated bytes values = 3;</code>
     * @return RepeatedField<string>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * values is a 2d-array of nq rows, every row contains a query vector.
     * for dense vector, all rows are of the same length; for sparse vector,
     * the length of each row may vary depending on their number of non-zeros.
     *
     * Generated from protobuf field <code>repeated bytes values = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setValues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool element_level = 4;</code>
     * @return bool
     */
    public function getElementLevel()
    {
        return $this->element_level;
    }

    /**
     * Generated from protobuf field <code>bool element_level = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setElementLevel(bool $var)
    {
        $this->element_level = $var;

        return $this;
    }

}

